### ISSUE TITLE
Setting up editing environment on a new computer

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#100]
I've just got my new PC which I'm hoping I can use for the atlas (among photo editing and work etc.) - I'm trying to remember all the stuff we went through in the meeting a couple of weeks back to set up the environment needed to make changes? I've installed atom and github and I think made a successful edit (without the .Renviron file?) but haven't done any of the docker/cygwin stuff required for the building of assets. I've got windows 10 pro now so it should be all good.

Wondering if it would be worthwhile having something in the wiki for all the setup stuff?

**Comment by jeffreyhanson** [comment]
Yeah, I agree - it's definitely worth having something in the wiki that describes the complete setup. How about something like this:

Atlas administrators will need the following programs installed to edit files locally and push changes to the repository: (i) [Atom](https://atom.io/) (or other text editor) and (ii) [GitHub client](https://desktop.github.com/) (or other Git interface). To make local previews of the atlas or build assets locally, administrators will also need, in addition to the previous programs, (iii) the [Docker client](https://www.docker.com/get-started), and (iv) [Cygwin](https://www.cygwin.com/) installed (only if using Windows). To push assets to the repository's online storage, in addition to the previous programs, administrators will also need (v) the `.Renviron` file with the GitHub token (this can be obtained by emailing one of that atlas administrators) copied into their "My Documents" folder (or equivalent on other operating systems).

**Comment by dbl3raf** [comment]
looks great @jeffreyhanson

**Comment by jeffreyhanson** [comment]
I've added a new FAQ with this info (https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#as-an-atlas-administrator-what-programs-and-files-will-i-need-on-my-computer) - so I'm closing this issue now.
