### ISSUE TITLE
Add information about surveyor sheets to wiki

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#102]
This needs #65 to be finished first.

**Comment by jeffreyhanson** [comment]
I've updated the wiki pages with regards to the changes made along with the surveyor sheets, for reference these include:

* [How can I remake all of the the species' graphs, maps, tables, and interactive widgets, and the surveyor sheets too?](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-remake-all-of-the-the-species-graphs-maps-tables-and-interactive-widgets-and-the-surveyor-sheets-too)
* [How can I specify (or not) if a species should appear in the surveyor sheet checklists?](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-specify-or-not-if-a-species-should-appear-in-the-surveyor-sheet-checklists)
* [How can I specify (or change) the name of an atlas grid cell?](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-specify-(or-change)-the-name-of-an-atlas-grid-cell)
* [How can I specify (or change) the checklist, kilometre, or minute target for an atlas grid cell?](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-specify-or-change-the-checklist-kilometre-or-minute-target-for-an-atlas-grid-cell)
* [How can I specify (or change) the description of an atlas grid cell?](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-specify-or-change-the-description-of-an-atlas-grid-cell)
* [How can I alter the formatting of the checklists in the surveyor sheets?](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-alter-the-formatting-of-the-checklists-in-the-surveyor-sheets)
* [How can I customize the appearance of the imagery in the surveyor sheets?](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-customize-the-appearance-of-the-imagery-in-the-surveyor-sheets)
* [How can I change the text which appears on the last page of the surveyor sheets?](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-change-the-text-which-appears-on-the-last-page-of-the-surveyor-sheets)
* [How can I update the atlas with a new version of the eBird data set?](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-update-the-atlas-with-a-new-version-of-the-ebird-data-set)
* [I get an error when I try pushing new assets?](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#i-get-an-error-when-i-try-pushing-new-assets)

I've also updated the [Data](https://github.com/bird-team/brisbane-bird-atlas/wiki/Data) and [Atlas maintenance](https://github.com/bird-team/brisbane-bird-atlas/wiki/Atlas-maintenance) wiki pages too.

**Comment by jeffreyhanson** [comment]
@dbl3raf and @Louis-Backstrom, can you let me know if I've missed anything in the wiki?

**Comment by Louis-Backstrom** [comment]
Looks great @jeffreyhanson !

**Comment by dbl3raf** [comment]
As ever @jeffreyhanson this is amazing - I've taken a read through the wiki and only found a couple of minor typos. With enormous thanks to you, I'll close this issue.
