### ISSUE TITLE
What's the best way to store additional files for reference?

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#103]
As the project goes on, we'll need to store a number of additional files that contributors might want to look at, e.g. lists of reference material that we need to search through, additional information about species etc etc. What's the best place to put this kind of stuff? They'll be spreadsheets and word docs etc. Can we create a folder in the repo to keep them, or should we set up an external dropbox account or something? For the sake of keeping everything in one place, the former would be ideal, but where would the material go?

**Comment by jeffreyhanson** [comment]
I think it depends on (1) how often will the files be updated, (2) should they be public, (3) is it important for them to be version controlled (e.g. view versions of them at specific dates like with the atlas itself), and (4) how big will the files be?

**Comment by jeffreyhanson** [comment]
Some possibilities:
1. If the files are small and they can be public, then we could just create a folder in the repo
2. If the files are big and they can be public and they won't get updated much, then we could creatre a release to store the material (like the assets).
3. If the files can't be public, then dropbox is probably the way to go.

**Comment by Louis-Backstrom** [comment]
I'm not quite sure what files we'd put here but I think trying to keep them in the same place as much as possible would be ideal. @jeffreyhanson for any files that are private - is there a way to password-protect github folders or something similar? Could we make a branch of the original that isn't public?

**Comment by jeffreyhanson** [comment]
Yeah, I agree keeping them all in the one place is ideal, but file size/permissions might complicate things. There isn't a way to make a private branch or private files on a public GitHub repo. One option might be to zip up "private" files and put a password on the zip file though. But I think perhaps a public GitHub repo isn't the right place to be storing private files. If you wanted to have everything on GitHub, we could have a private GitHub repository, specifically for the private files and discussions - but that would mean upgrading the bird-team organisation to a paid tier ($25 per month, https://github.com/pricing)

**Comment by dbl3raf** [comment]
These are all public files, e.g. lists of journals and databases we have searched, additional information tables about species, sites etc etc. Various reference resources that will be needed as we build the content of the Atlas. Maybe we could make a resources folder - I'm not sure how to create a folder in the repo?

**Comment by jeffreyhanson** [comment]
Ok - and just to confirm - what is the expected file size? PDFs can take up a bit of space if they have high res images in them.

**Comment by Louis-Backstrom** [comment]
I don't think they'd be that big - it'd just be text and tables without any images probably. Creating a folder in the repo is easy from my experience - if they're not private I think this is the best way to go

**Comment by Louis-Backstrom** [comment]
I've created a `resources` folder in the main repo that we can put all these files in. Currently it only has one file - which I've created as a way of provisionally storing notable records not in eBird for addition later down the track (as per @dbl3raf thoughts). This will be populated as records are found etc.

**Comment by dbl3raf** [comment]
brilliant @Louis-Backstrom - closing issue
