### ISSUE TITLE
Datestamp for data release as well as last edit?

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#105]
I've just been wondering if it might be good to have a datestamp for the eBird dataset we're using as well as for the date of the last published edit? Something like "Current Dataset: October 2018 Release" underneath the datestamp we've already got on the front page. Might be good just so users know that the data is up to date (but also not real-time / daily updates like the atlas itself is)

I'd imagine this could just be done manually each time we update the data but I guess it could probably be automated too? Wouldn't think it'd be worth the effort.

**Comment by jeffreyhanson** [comment]
Yeah, I think this is a great idea.

**Comment by jeffreyhanson** [comment]
Hmm, the pdf version doesn't show the date-time stamp so we will need to put the atlas data version somewhere else (i.e. any where other than the YAML header in the `index.Rmd` file).

**Comment by jeffreyhanson** [comment]
I've updated the book to display the data version in the Methods chapter (see here once the book website has been rebuilt: https://brisbanebirds.com/methods.html). If you can think of a better place/way to mention the data version, please feel free to edit it. You just need to use the `'r data_release_month_year'` to insert the month/year (replacing apostrophes with back-ticks).
