### ISSUE TITLE
General preferences for species referencing?

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#106]
Just wondering if we had preferences for general sources to use e.g. when describing particular species. Do we want mostly HANZAB, HBW, other sources, or combinations thereof? These sources are useful in the opening sections of the accounts when describing what the species looks like as well as general comments about the behaviour - I think it's good that the atlas focuses on the distribution of birds within the region rather than their ID (as most users will have access to a field guide at the very least) - but it would be good to have a decent sized section on ID I think for most species.

**Comment by dbl3raf** [comment]
I think we should use ABG - it's the best field guide, and most readers won't have HANZAB or HBW. I think we should be very brief with ID - our purpose is definitely not to write an ID guide here

**Comment by Louis-Backstrom** [comment]
Sounds good - I've got a couple of references for HANZAB in currently, but mostly for the stuff that is finer details e.g. on breeding times and such. I'll add a reference to ABG into the bib file for future use.
