### ISSUE TITLE
Errors building surveyor sheets

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#108]
Two different errors received so far - the build of surveyors sheets successfully gets part way through then collapses. I've emailed @jeffreyhanson the error screens

**Comment by jeffreyhanson** [comment]
I've updated the code for grabbing the observer names to wait a bit between multiple attempts, so maybe try fetching the latest version and see if that fixes it?

**Comment by dbl3raf** [comment]
Thanks - trying it now

**Comment by dbl3raf** [comment]
so near but yet so far - all assets built just fine, but errored just now during upload. It tried lots of times to do the MacKenzie sheet - I've restarted the push
![image](https://user-images.githubusercontent.com/23551540/49576077-f6241700-f98f-11e8-9b4e-1c8c097ad6cf.png)

**Comment by jeffreyhanson** [comment]
Hmm, did you check the surveyor sheet release to see if that file has been corrupted and manually needs to be deleted?

**Comment by dbl3raf** [comment]
yes - there was no sign of that file in the release. The push just failed again, this time on a different file; I wonder if it's to do with trying to do this on home internet - it's a big upload!
![image](https://user-images.githubusercontent.com/23551540/49580077-ced24780-f999-11e8-87e8-9f74f5d55cdf.png)

**Comment by dbl3raf** [comment]
I'm getting NBN tomorrow - bet it definitely won't work then :-)

**Comment by dbl3raf** [comment]
just failed again, but then I realised they were in there with red squares - I'd forgotten I needed to edit the release first, before I would see them.

**Comment by jeffreyhanson** [comment]
Ah ok - great - fingers crossed it works now.

**Comment by dbl3raf** [comment]
new error now, happened twice in a row - I've deleted the corrupt zip file from the release after each error
![image](https://user-images.githubusercontent.com/23551540/49613633-c4dd3280-f9f3-11e8-811e-57eaa447e51a.png)

**Comment by dbl3raf** [comment]
I think it's just my unstable home internet connection - I'll try it next time I'm in the office.

**Comment by jeffreyhanson** [comment]
Ok - yeah - I haven't seen that error before

**Comment by Louis-Backstrom** [comment]
I would try to make / push the assets myself (as I need practice and hopefully my internet is stable) - but I've forgotten how we did it. The wiki [https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-remake-all-of-the-the-species-graphs-maps-tables-and-interactive-widgets-and-the-surveyor-sheets-too](url) helps but I can't run `make pull_image` in cmd. I've got docker running etc. but I think I'm missing a step.

**Comment by dbl3raf** [comment]
do you have the .Renviron file in C:\Users\USERNAME ?

**Comment by dbl3raf** [comment]
still failing on upload of assets 
![image](https://user-images.githubusercontent.com/23551540/49673869-a8a4c880-fabb-11e8-8a26-49d12247ca7b.png)

**Comment by dbl3raf** [comment]
it worked! I hadn't been deleting the zip files - just the actual sheet with a red cross. Finally I followed @jeffreyhanson instructions on the wiki, and it worked perfectly. Closing issue.

**Comment by jeffreyhanson** [comment]
Glad to hear it finally worked!

**Comment by jeffreyhanson** [comment]
I've just updated the code to save the surveyor sheet grid maps as jpeg files (instead of png files) - this should hopefully reduce the size of the surveyor sheets and reduce the chances of encountering problems on shaky/slow internet connections.
