### ISSUE TITLE
Omit some locations from Atlas datafile

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#109]
If you take a look at the map in the Lower Joyners Ridge grid square, there is a general hotspot located there for the entire D'Aguilar National Park. This is "polluting" the grid square with 103 species, despite the fact no eBirder has ever actually visited the square!
![image](https://user-images.githubusercontent.com/23551540/49685700-a41bf680-fb33-11e8-840c-d76e9de56e9d.png)

A solution to this would be to add a list of exceptions - things to be omitted from the Atlas datafile as a preliminary processing step.

How easy would it be to implement something like this @jeffreyhanson ? This will also be a problem in a few other grid squares, so not limited to just this one.

**Comment by jeffreyhanson** [comment]
Not too tricky. Should such localities be excluded from ALL aspects of the atlas (e.g. the maps + graphs in the atlas and also leader boarders and surveyor sheet checklists), or simply not be displayed in the surveyor sheets?

**Comment by jeffreyhanson** [comment]
Also, for consistency, the localities to be excluded should be referred to by their ID in eBird - is this something you can easily find out from the eBird website?

**Comment by Louis-Backstrom** [comment]
It is for public hotspots, not so sure for private personal locations. For hotspots it's in the url - https://ebird.org/australia/hotspot/L2559475 this is the offending location in @dbl3raf's post.

**Comment by dbl3raf** [comment]
yes, the location ID for personal locations is easily found out from the eBird website / dataset

**Comment by jeffreyhanson** [comment]
Ok - @dbl3raf and @Louis-Backstrom, can you please confirm if such localities should be excluded from ALL aspects of the atlas (i.e. omitted immediately after reading in the data) or if they should simply not appear in the maps for the surveyor sheets (but the data associated with these localities should be included in all maps/graphs/leaderboards/checklists/tables, etc)?

**Comment by Louis-Backstrom** [comment]
I'm inclined to suggest that they be excluded from everything. The location (especially in this particular instance) is so vague, the data may not even be inside Brisbane so I think it's easier just to invalidate it all.

**Comment by dbl3raf** [comment]
Yes, locations on this list should be excluded from everything - they are locations that are still eligible to remain in the eBird database, but are completely unsuitable for Atlassing. It won't be hundreds of sites - just a couple of dozen max I would think. We need to use this list very sparingly - it will mainly be for cases where there is a hotspot or personal location covering a very general area that spans many kilometers and is impossible to geolocate accurately. For the most part, other kinds of problematic locations will be removed from the underlying eBird database by eBird regional reviewers.

**Comment by jeffreyhanson** [comment]
I've added a new spreadsheet to manage which localities should be excluded (https://github.com/bird-team/brisbane-bird-atlas/tree/master/data/localities), please see the new wiki page for instructions on using it: https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-specify-which-ebird-sampling-localities-eg-hotspots-should-be-excluded-from-the-atlas
