### ISSUE TITLE
CircleCI Builds taking 2x longer than previously

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#113]
I've noticed of late that the website builds now take twice as long as they used to - around 1:30 rather than 45min. Looking back through the builds it seems between #271 and #285 (all between failed) is where the change happened. Am I right in believing this is when we added in the surveyor sheets and that's where the difference is coming from?

And can we decrease it? It's obviously not a massive issue but it would be nice to be able to.

**Comment by jeffreyhanson** [comment]
Yeah I don't know why the builds have slowed down, two potential reasons might be: (i) the atlas now downloads a 1.5GB zipfile with the surveyor sheets and/or (ii) it now reads in the eBird data set to find out what version it is (i.e. month/year of the the latest record). But I wouldn't expect either of these reasons to result in a 45 minute increase in build time.

**Comment by dbl3raf** [comment]
shall we close this issue, if there's nothing obvious to investigate here?

**Comment by Louis-Backstrom** [comment]
Yep, I don't think it's a massive issue at this point - if the builds start taking even longer it might be worth reopening but for now, not a priority.
