### ISSUE TITLE
Surveyor sheet pdf files in wrong place

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#121]
I just noticed that a bunch of surveyor sheets have been uploaded to the "Atlas asset and document storage" release and not the "Atlas surveyor sheet storage" release where they should be stored. Does anyone know how this happened? Is this due to a bug in the `make push_assets`? The atlas website will assume that surveyor sheets are in the "Atlas surveyor sheet storage" release, so the pdfs in the "Atlas asset and document storage" release will not be used.

**Comment by Louis-Backstrom** [comment]
Weird. I certainly don't think I changed anything or ran any erroneous commands that could have done that - but I guess given it's an issue that's seemingly happened since I started playing around with the assets it's likely to be my fault. I'll see if the [next run](https://github.com/bird-team/brisbane-bird-atlas/issues/119#issuecomment-468978435) fixes it?

**Comment by jeffreyhanson** [comment]
Ok sounds good. If the files are still there after your next run, we can just delete them manually.

**Comment by Louis-Backstrom** [comment]
Okay, I believe I've manually uploaded the latest surveyor sheet files to the correct storage. The website seems to be behaving as expected with them as well, so I think it's fixed. Two things to do now:

1. Work out why this issue happened in the first place (my suspicion is a bug in one of the commands, or something happening as a result of `make push_assets` aborting before it had uploaded all the sheets - does it upload them first to "Atlas asset and document storage" and then move them to "Atlas surveyor sheet storage" ?)

2. Delete the erroneous files in "Atlas surveyor sheet storage" - I'll let @jeffreyhanson do this so I don't break anything ;)

**Comment by jeffreyhanson** [comment]
Ok - I've deleted the erroneous files.

**Comment by Louis-Backstrom** [comment]
Even though the `make push_assets` still failed, the surveyor sheets that did upload seemed to go in the right place so I'm going to close this issue for now until this problem arises again.

**Comment by jeffreyhanson** [comment]
Ok sounds good - thanks
