### ISSUE TITLE
Decision on list of common names to be used

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#127]
We need to decide on a common name list to follow, as currently the names used in the Atlas are a mix between various lists - and the working list also doesn't line up with the species list.

Some options:
eBird main - probably most in line with our data, but a lot of the names are strange and not used widely in Australia so will be confusing (e.g. Black-bellied Plover, Blue-breasted Quail)
eBird aus - what most people see when they look at their eBird, so would be familiar. Probably the best option, but I don't know where to get a list of them. [Apparently Mat Gilfedder came up with them?](https://help.ebird.org/customer/portal/articles/1596582-common-name-translations-in-ebird?b_id=1928)
IOC - also widely used, so familiar to a lot of people, although some names are less liked (e.g. Maned Duck). Also updates a lot, so we'd have to keep up.
WLAB - "official" list and uses a lot of the most common names, so would be a pragmatic choice. Somewhat outdated now unfortunately, but v3.0 should be coming out soon - so maybe we adopt that when it comes out?

@dbl3raf  thoughts?

**Comment by dbl3raf** [comment]
eBird Australia is perhaps the best option, as the taxonomy will match ours exactly, and this is what people are seeing on eBird. Are there any weird names out there on the eBird Australia list? I can't think of any obviously problematic ones

**Comment by Louis-Backstrom** [comment]
Nothing really weird, no - a couple of species will have an even split of common name usages so we will have to just accept them (e.g. Eastern/Pacific Koel). From a search through the entire eBird Aus list:

Brown Cuckoo-Dove (Australian) - would we just omit the "(Australian)"? Not really sure why it has it like that, it's the only full species with parentheses in the name. 

Is the only one that stuck out as weird. Everything else is at least an accepted name in usage, even if there are alternatives. I'll try and get round to sorting out both lists (species and working) to conform to this, then we can update should there be any changes. Is there a way we could get notified of any australian english name changes? Do they happen alongside the taxonomy updates?

**Comment by Louis-Backstrom** [comment]
I guess the other question is what order/broader taxonomy do we use? At the moment it seems we're using eBird species names (which makes sense from a data entry perspective), but the order of species follows WLAB?

**Comment by dbl3raf** [comment]
The issue on my mind when choosing WLAB was whether public familiarity / acceptance is greater for WLAB than eBird, but maybe it doesn't matter too much? I guess strictly following eBird Australia for names, taxonomy and sequence would be the cleanest decision, and it is frequently updated to capture latest splits etc. I'd be happy with switching to eBird Australia for everything

**Comment by dbl3raf** [comment]
> Brown Cuckoo-Dove (Australian) - would we just omit the "(Australian)"? Not really sure why it has it like that, it's the only full species with parentheses in the name.

Not entirely sure - but we can remove the parentheses and still be almost completely consistent with eBird Australia

**Comment by dbl3raf** [comment]
> Is there a way we could get notified of any australian english name changes? Do they happen alongside the taxonomy updates?

I don't think there's an automatic way to get updated, but when there is a taxonomy update we can try to get wind of any changes and implement them

**Comment by Louis-Backstrom** [comment]
Commit 098d31a attempts to change the species ordering to eBird 2018 taxonomy in the `atlas_list.xlsx` and `ABB_WorkingList_v1.0.xlsx` files, as well as changing a handful of names to conform with eBird Australia names for use in the Atlas. *Hopefully* this commit works fine, and I can close this issue.

**Comment by Louis-Backstrom** [comment]
Right, I believe with cdc0854 this issue is now resolved. Common species names should conform to eBird Australia, and the order is good as well. For future taxonomic updates we can open new issues.
