### ISSUE TITLE
Prepare draft page as a template

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#13]

**Comment by jeffreyhanson** [comment]
I stumbled across the BC Breeding Bird Atlas (http://www.birdatlas.bc.ca/site-tour/), which might offer some inspiration. I like how it has a "fact box" with a few summary statistics (e.g. elevation range, threat status; see http://www.birdatlas.bc.ca/accounts/speciesaccount.jsp?sp=BLOY&lang=en).

**Comment by dbl3raf** [comment]
[Magpie Goose.docx](https://github.com/bird-team/brisbane-bird-atlas/files/2058065/Magpie.Goose.docx)

Here's a very first go at Magpie Goose - this isn't really a draft that can inform styling yet, but I wonder if you'd be able to produce the maps and graphs for this species, so I can mock up a real draft template and then send it to a couple of other folks? As you can see I'm in desperate need of artistic inspiration!

For the main photo - I think we should use Facebook profile pic dimensions (120 x 63); will need careful pic selection of course, but that's OK.

I think maps should go summer then autumn on the top row, then winter, spring on the bottom row.

Graphs should be habitat then elevation on top row, then year, month on bottom row

**Comment by dbl3raf** [comment]
we could add a third column of things in the fact box - I'm completely open to any suggestions you've got on anything!

**Comment by jeffreyhanson** [comment]
I think I've updated the html and pdf templates to match those in the magpie goose example. @dbl3raf, can you look at the online web version (https://brisbanebirds.com/magpie-goose-anseranas-semipalmata.html#magpie-goose-anseranas-semipalmata) and the offline pdf version (https://github.com/bird-team/brisbane-bird-atlas/raw/gh-pages/brisbane-bird-atlas.pdf) and let me know what you think of the layouts? In a different issue, you requested the ability to have subsets of graphs (e.g. to drop reporting rate per month for non-migrants) so the demo includes species with two graphs (https://brisbanebirds.com/plumed-whistling-duck-dendrocygna-eytoni.html#plumed-whistling-duck-dendrocygna-eytoni) and one graph (https://brisbanebirds.com/wandering-whistling-duck-dendrocygna-arcuata.html), can you please confirm if these graphs are handled correctly (i.e. the image is made as big as possible to fill the space)?

**Comment by dbl3raf** [comment]
Brilliant Jeff, these all look great - yes that handling looks good, with the graphs expanding to fill the space available. I think this issue can be closed.

**Comment by jeffreyhanson** [comment]
Ok - great - I'll close this then
