### ISSUE TITLE
Page numbering of Book incorrect

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#131]
I've noticed that the page numbering used in the book is probably not how we want it:

![image](https://user-images.githubusercontent.com/44354406/54798230-65a1e600-4ca3-11e9-9ada-d615c1104651.png)

I'm assuming we want either:

All front matter - Roman numerals
All species accounts - Hindu-Arabic numerals
All back matter - Roman numerals

Or:

Title, welcome, contents - Roman numerals
Rest of front matter - Hindu-Arabic
Species accounts - Hindu-Arabic
All back matter - Roman

Currently it's got the entirety of the species accounts under Roman numerals, which doesn't follow convention as far as I can tell.

What's more, the acknowledgements pages come before the contents, which seems odd to me. I think the order (and then we can work out roman/hindu-arabic from there) should be:

Title page
Contents
Welcome
Introduction
Brisbane's Environment
Methods
Contributing
Gazetteer
Newsletter
[Acknowledgements]
Species Accounts (intro, then all of them)
[alternate Acknowledgements]
References
Index

I'm going to try and work out how to change this ordering - hopefully I don't break the build.

**Comment by dbl3raf** [comment]
sounds good @Louis-Backstrom

**Comment by Louis-Backstrom** [comment]
fixed :)

**Comment by jeffreyhanson** [comment]
Awesome - thanks!
