### ISSUE TITLE
Consider alternatives to CircleCI

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#134]
Further to discussions in #129 and via email etc - I think we should consider other options to CircleCI for building the website, seeing as it seems the only option with them from here is to massively downsize the Atlas or pay up. I am totally out of my depth here, so I wholly defer to @jeffreyhanson and @dbl3raf judgement - but thought we should open a separate issue to discuss things here.

Is there a reason we can't use Travis for both website and book?

**Comment by jeffreyhanson** [comment]
The reason I went to CircleCI for the website was because Travis has a build limit of 60 mins which is too short for the website. For $69 USD per month (https://travis-ci.com/plans), we could switch to Travis for the website but this is not ideal.

**Comment by Louis-Backstrom** [comment]
So I take it Travis's statement "Always free for Open Source" has a number of caveats then.

Are there other options available? A brief look online (once again, with very little background to know what I'm looking for/at) turned up [Jenkins](https://jenkins.io/)?

**Comment by jeffreyhanson** [comment]
Well, yeah its free- but if you want really good build environments you have to pay (but this actually pretty reasonable, I mean Travis does an amazing job even supporting open source stuff for free).

I haven't tried Jenkins - but I'm not sure if you need to install it on your own server or not?

**Comment by dbl3raf** [comment]
If it is a simple, predictable pricing structure, I'm happy to pay USD70 monthly for Travis - shall we go ahead and set it up?

**Comment by Louis-Backstrom** [comment]
> Well, yeah its free- but if you want really good build environments you have to pay (but this actually pretty reasonable, I mean Travis does an amazing job even supporting open source stuff for free).
> 
> I haven't tried Jenkins - but I'm not sure if you need to install it on your own server or not?

Yeah - obviously wasn't expecting it to be free no matter what! My experience so far has been excellent with Travis. It might be worth contacting them directly and seeing if they're flexible with the plan and can tailor something more specifically to our needs @dbl3raf ?

**Comment by jeffreyhanson** [comment]
Sounds good but before we go with the paid option, could @dbl3raf or @Louis-Backstrom try remaking the graphs as per instructions in #129 first and see if that fixes it first?

**Comment by Louis-Backstrom** [comment]
On it

**Comment by jeffreyhanson** [comment]
Thanks!

**Comment by jeffreyhanson** [comment]
I'm trying out Semaphore (https://semaphoreci.com/). They recently overhauled their systems, so we might be able to use this now for the website.

**Comment by jeffreyhanson** [comment]
So it looks like it's the interactive maps that are causing the problem. I tried simply skipping them when creating the website and this meant CircleCI could complete the website build in 2 minutes as opposed to >1 hour.

**Comment by jeffreyhanson** [comment]
I've been playing around with how interactive maps are embedded into the atlas website and have managed to get the build working again with CircleCI. Also the website now builds in <15 mins too which is nice. So, I'll close this issue now. If you notice anything strange or ugly about the way the interactive maps now appear in the atlas, please create a new issue and add a style tag.

**Comment by Louis-Backstrom** [comment]
That's so strange... Guess that solves our issues for the moment now.

Is there a way of telling how resource intensive the new builds are? So that we know if we still need to consider alternatives in the future once we start increasing the load? Purely based off how quick the builds now are I doubt it'll be an issue very soon but I don't really know.

Have created a style issue in #138.

**Comment by jeffreyhanson** [comment]
Well, it's not strange per se - just a bit complicated. Basically, instead of directly adding the maps to the atlas' web pages, the maps are now each located in their own web page which is imported by the atlas' web pages when the user views them. When building the atlas, the bit that takes the longest is converting from the markdown format to the web page format. By "removing" the maps from the conversion process, it means the conversion process doesn't have to worry about any markdown stuff contained in the maps---even though there isn't markdown in our maps, it still needs to check and account for the possibility which increases run time and resource needs. Does that make sense? If not, I can try explaining again.

I think this has substantially reduced the resources needed for building the website (both in terms of RAM needed + total time). Yeah, I'm hoping this will mean that unless we add 5 times the number of current species we don't need to worry about exhausting CircleCI's free-tier limits.

**Comment by Louis-Backstrom** [comment]
Right, that makes more sense now yep - still a curious situation but glad that we've worked it out!
