### ISSUE TITLE
Minor style issue in new maps

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#138]
![image](https://user-images.githubusercontent.com/44354406/55761348-4d530900-5aa2-11e9-8ef4-d5ff06754d9a.png)

I can't find a comparison pic but the text for the seasons box is now smaller than it used to be - it's not unworkable or anything but it would be nice (if simple) to revert it back to the original size. Is that doable?

**Comment by jeffreyhanson** [comment]
Done.
