### ISSUE TITLE
Style issue in book

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#139]
This is potentially a personal preference thing, but for the book, is it possible to have it such that the two-column layout sections fill one column then the next rather than trying to fill both evenly? Especially at the end of species texts, it can look quite weird to have two columns up the top:

![image](https://user-images.githubusercontent.com/44354406/55862736-66e87380-5bbc-11e9-8e50-50b9c66521db.png)

Is this achievable?

**Comment by jeffreyhanson** [comment]
I've just pushed a patch which should hopefully fix this problem. Hopefully, we can see that this fixes the issue in the atlas when the Travis build finishes.

**Comment by jeffreyhanson** [comment]
The patched worked, so I'll close this issue now.

**Comment by Louis-Backstrom** [comment]
Awesome, thanks @jeffreyhanson
