### ISSUE TITLE
Change grid resolution to 1 km

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#14]

**Comment by dbl3raf** [comment]
Jeff - I've changed my mind after looking through a bunch of maps last night - 2km resolution is the correct one. Brisbane LGA is to large for a 1 km map - I might upgrade to that in 2030 when bird data is 100x denser than it is now

**Comment by jeffreyhanson** [comment]
Note that 54dc6910e8312c3ea758dff1021ce5d6cd6cd12e is not related to this issue and was a typo.
