### ISSUE TITLE
eBirder names no longer appearing on Surveyor Sheets

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#141]
The latest batch of surveyor sheets (March eBird update, did them about a week ago but only just noticed) have no names attached to the observers in the top 5 table. At a guess, I suspect this is because eBird just overhauled the [checklist page design](https://ebird.org/news/new-checklist-view-in-ebird) and the name scrubber is having trouble:

![image](https://user-images.githubusercontent.com/44354406/56872707-6c283800-6a6f-11e9-9820-5142ae94a138.png)

I don't know enough about the script that finds the names to really have any idea how to fix this but if I can work it out I'll give it a shot. Otherwise I think we need @jeffreyhanson's expertise

**Comment by jeffreyhanson** [comment]
Hi - thank you very much for looking into this! Yeah, the new checklist webpage is probably causing this issue. If you wanted to try fixing this, the relevant code is line 27 in `code/functions/find_observer_name`. I'll try taking a proper look at this tonight to see what I can do.

**Comment by Louis-Backstrom** [comment]
yep, managed to get that far but couldn't work out what "dd strong" meant (which I suspect is what needs to be changed). Should hopefully be straightforward though.

**Comment by jeffreyhanson** [comment]
I've just pushed a patch which should fix this - could you please try remaking the surveyor sheets to see if this fixes it?

**Comment by Louis-Backstrom** [comment]
Remaking assets at the moment. Will update when I get home tonight.

**Comment by Louis-Backstrom** [comment]
No good, still NAs :(

**Comment by jeffreyhanson** [comment]
Sorry about that. It seems to be working on my computer - could you please double check if you pulled the latest version of the atlas to your computer before running the command to remake the sheets?

**Comment by Louis-Backstrom** [comment]
Hmm okay, I'll try and do a full refresh build later - I won't be home until later tonight so I'll start it all then.

**Comment by Louis-Backstrom** [comment]
![image](https://user-images.githubusercontent.com/44354406/57069956-5fc70800-6d19-11e9-9a3e-a414b1ad6be7.png)
Have hit this error twice now on `make assets` - I think it's probably just a standard out of resources error but it happens at the same place each time, and I've allocated plenty of resources (8GB/5 cores) to Docker...

**Comment by Louis-Backstrom** [comment]
Fixed itself up. Not sure what the error was but it was fixed when I ran `make pull_assets` first before `make assets` - closing issue.
