### ISSUE TITLE
More asset build errors

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#142]
Have been trying to remake the assets over the past couple of days, to update to the May dataset & fix a few other changes I've made since the last update - but I keep getting an error right when it gets to starting the graphs - doesn't give me anything other than the double "Killed" line :/

I have tried changing resource allocation for docker (8GB/4 Cores) and changing the parameters, and have done every permutation I can think of of removing old assets, using/not using pull_assets beforehand, removed and redownloaded the latest build image etc. 

All I can think of is the new .png optimisation might be throwing up problems?

**Comment by jeffreyhanson** [comment]
Hmm, that's annoying. The "killed" line means that the Docker container is running out of memory. Have you tried allocating all your RAM to Docker (i.e. if your computer has >8GB RAM could you try increasing it)? Another option might be setting the number of threads to one in the `parameters.yaml` file? If that doesn't work, I'll need to try updating the code to use less RAM.

**Comment by Louis-Backstrom** [comment]
12GB and only 1 core in parameters seemed to fix it overnight - I suspect it just really hates using more than one core for whatever reason, which is annoying given I've got six but oh well. Assets should all be updated now.
