### ISSUE TITLE
Backup Old Assets at start of new rebuild

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#145]
A random thought I was having today - I think it would be good if, at the start of each new `make assets` rebuild the system backed up the current set of assets to a .zip folder or similar, so that one can easily compare the two versions and ensure that the desired outcome has been reached.

This is especially useful when rebuilding assets after a data update, to ensure that it has actually gone through, or after a functional change to the code (e.g. changing the surveyor sheet formatting).

I think you could probably also put it in a folder with .gitignore (?) such that it is only kept locally on the user's computer and doesn't take up unnecessary space on the repo?

Something like:

`make assets`

*compress current \assets folder into a new `assets-backup.zip` folder which gets placed in old\assets-backup*

*delete current assets folder*

*continue on as per current code*

Does that make sense / sound possible?

**Comment by jeffreyhanson** [comment]
Great idea - done!

**Comment by Louis-Backstrom** [comment]
Awesome! Thanks @jeffreyhanson
