### ISSUE TITLE
Fix annoying comments in dataset

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#146]
A "bug" that's been annoying me in this project for some time now (and just caused me a whole lot of headaches in a personal side project I've been doing this week) - whenever people put certain characters (e.g. ", ', maybe some others I don't know) into their species or checklists comments this throws the whole process out of wack and causes problems with the asset building - I think our code is robust enough to just ignore the line and move on (the silvereye example springs to mind), but I figure we could probably avoid the problem altogether if we just remove those two columns from the data straight away before anything else?

Does that make sense?

**Comment by Louis-Backstrom** [comment]
Or alternatively, change the quote character in the read stage?

**Comment by jeffreyhanson** [comment]
I didn't know this was causing issues - thank you for letting me know. I'll have to thank about this because it's not just as straightforward as telling R not to read in these columns - because we only tell it to ignore the columns after it has correctly identified the columns which is the very issue causing these problems. We might have look into some more advanced methods such as using the auk R package to ingest the data to address this issue (https://github.com/CornellLabofOrnithology/auk).

**Comment by Louis-Backstrom** [comment]
In data.table::fread(record_path, data.table = FALSE) :
  Found and resolved improper quoting out-of-sample. First healed line 31279: <<URN:CornellLabOfOrnithology:EBIRD:OBS680234213  2018-11-26 17:52:00.0   25487
species Silver-eye      Zosterops lateralis                     X                               Australia       AU      Queensland      AU-QLD  Brisbane     AU-QLD-BRI                                       Toohey Forest Conservation Park L2559772        H       -27.54115       153.05191       1988-04-13      06:10:00      obsr302493      S50190935       Historical      P62     EBIRD                           1       0               0       1       0               Birding near our quarters in the QE2 stadium in trails around the Toohey Forest and the Griffith campus       "Seen in small groups in the woods" and seen regularly around QE II for the rema>>. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.

This is the message - it's not an issue because I think it just ignores them but still retains the entry itself.

I've played around with auk a bit myself - I'm not sure if it will do what we want it to do, and likely not as well as data.table currently is? Only just getting stuck into either package though, so will defer to your vastly greater expertise.

**Comment by jeffreyhanson** [comment]
Ah - ok. Yeah, I agree - I think it's just a reporting potential issue but saying that it fixed the data. Well, auk is specifically designed to work with eBird data so it should work better then data.table - but we might need to play with the code to get it working with the atlas.

**Comment by Louis-Backstrom** [comment]
Can we try adding in the `quote = ""` parameter to the `fread()` function? I've used this with eBird data before and it seems to fix weird character problems like this without any side effects?

I've done it before on the entire ebd_AU dataset so don't see why it would cause problems in the BNE data, which is just a subset thereof?

**Comment by jeffreyhanson** [comment]
Sure - I'll do that now.

**Comment by jeffreyhanson** [comment]
Did this fix the annoying messages?

**Comment by Louis-Backstrom** [comment]
Yes, it appeared to. Closing for now.
