### ISSUE TITLE
Book color theme

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#15]
Bookdown supports the several colour themes (including the default, see here for example: https://bookdown.org/yihui/bookdown/theming.html) and the bootswatch colour themes (https://bootswatch.com/). @dbl3raf, can you specify which color theme the online version of the atlas should use?

**Comment by dbl3raf** [comment]
Journal looks good - the main body text seems nice and readable - a key feature I think

**Comment by jeffreyhanson** [comment]
As discussed in the hallway, implementing this issue will take longer than originally anticipated so we will leave it for now.
