### ISSUE TITLE
Book build broken - missing files

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#151]
I think the book code needs updating - the latest errors say `assets/graphs/Anseranas-semipalmata.png` is missing - because all graphs are now in jpg form... Does this need to be fixed?

**Comment by jeffreyhanson** [comment]
Ah - it looks like we are using the .jpgs for the website and the .pngs for the pdf of the atlas - and I  forgot about this. I suspect my reasoning at the time was that the .pngs will look nicer if (ever) printed to paper - but this is at the cost of the book pdf file being larger and the zipfile on GitHub being larger too. What do you think? Is it worth keeping the .pngs for the pdf book? Or simply use the .jpgs for the website and the .pdf book?

**Comment by Louis-Backstrom** [comment]
Yeah, not sure. I prefer .png files in general, especially for non-photo content (like the graphs) because it does look nicer - is it a significant change?

I think given that the book is in no immediate danger of being mass-produced we can probably safely change it to make using .jpg files - and theoretically it shouldn't be too challenging to change back in the future should we want to?

**Comment by jeffreyhanson** [comment]
Yeah, I generally prefer png files too. I don't really think the costs of supporting .png and .jpg files are too bad, shall we just keep it the way it was and have .jpg for website and .png for pdf?

**Comment by Louis-Backstrom** [comment]
Sure, sounds good to me - can you make that change?

**Comment by jeffreyhanson** [comment]
Yeah - it just requires reversing the change we made to delete the .png files when building assets.

**Comment by jeffreyhanson** [comment]
I've just push the fix to GitHub, so if you pull the latest version of the atlas and remake the assets, it should create the .png files.

**Comment by Louis-Backstrom** [comment]
Hmmm, it seems that the latest build didn't fix this - still no .pngs in the assets folders where there should be. I'm _fairly_ sure I did a pull of the latest build and image just before I did the latest remake, so I'm going to reopen this for now. 

Will do another remake of the assets once we have #149 up to the next stage and update here as well.

**Comment by jeffreyhanson** [comment]
When remaking the assets did you already have the previous version of the assets in your assets folder? If so, the code probably detected that the graphs were already made and just skipped them.

**Comment by Louis-Backstrom** [comment]
yes, I most likely did. When I next remake, I'll delete the entire `\assets` folder beforehand.

**Comment by jeffreyhanson** [comment]
Ah ok - thanks. If you want to reduce processing time and just remake the graphs (to add in the .png files), you could just delete all the jpgs in the `assets/graphs` folder.

**Comment by Louis-Backstrom** [comment]
Fixed in 331d045!

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much!
