### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#17]
I've been working on the code to produce the graphs for each species. I've included an example below, @dbl3raf can you let me know if you want any changes (e.g. layout, color, text size, etc)? 

Also, Richard Noske suggested that it might be good to try overlaying the records with broad-scale land-use (e.g. urban, rainforest, sclerophyll forest) or vegetation data and show the general patterns (e.g. as a barplot showing percentage of records per land-use category), what do you think?

![anseriformes-anseranatidae-anseranas-semipalmata](https://user-images.githubusercontent.com/3610005/40460219-e4e7ac72-5f48-11e8-83c6-ad01c983fff6.png)

**Comment by jeffreyhanson** [comment]
Since the maps show reporting rate, should these graphs also be updated to also show reporting rate (and use only data from checklists for the elevation plot)?

**Comment by jeffreyhanson** [comment]
(clicked button to close by accident)

**Comment by dbl3raf** [comment]
**Annual graph:**

1. Change y axis label to Reporting rate (%)
2. Calculate reporting rate from complete checklists only (reporting rate is thus the percentage of complete checklists in each year that contain the focal species)
3. Use data from 2006 - whatever the full latest year is (so currently 2017)

**Monthly graph:**

1. Change y axis label to Reporting rate (%)
2. Calculate reporting rate from complete checklists only (reporting rate is thus the percentage of complete checklists in each month that contain the focal species)

**Elevation graph:**

1. Do we have a boxplot-type option, so it can show the mean, a measure of spread, and outliers? Don't worry if not easy - we can get away with mean +/- SD or something like that

**A new graph showing habitats (as suggested by Richard Noske) is a great idea:**

1. It should look exactly like the annual graph, except instead of years the x axis categories are habitat types.
2. The 1:5 million Broad Vegetation Groups will do, for natural vegetation (the field name is DBVG5M - see https://www.qld.gov.au/environment/plants-animals/plants/ecosystems/broad-vegetation)
3. But I would like to further subdivide the "non-remnant" category within the BVG maps, so will need to work on this. Can you think of any other land use data sets? I'll need to sit and do some GIS for this. Although we could set up a dummy pretty quickly just using the BVG dataset linked above.

**Comment by dbl3raf** [comment]
Correction - for the annual graphs, please start them in 2005

**Comment by jeffreyhanson** [comment]
I'm still working with an older version of the data, so the graphs don't have data for some of the more recent years, but what do you think of this? The barchart shows all the vegetation groups in the Brisbane study area as they are named in the metadata, so let me know if you would like different labels (e.g. "Eucalypt forest" instead of "Eucalypt"). Also, what layout would you like for the graphs? One row, one column, or 2x2? 

<img src="https://user-images.githubusercontent.com/3610005/40583475-d01d8cc6-61d2-11e8-94ea-d6529d5f0b69.png" width=250>

**Comment by dbl3raf** [comment]
this looks brilliant!

1. A 2 x 2 panel would be good
2. start yearly plot at 2005
3. Change order of habitats to Rainforest, Eucalypt, Acacia, Mixed, Small-remnant, Non-remnant, Urban, Wetlands, Water, Mangroves, Estuary, Ocean (I will provide a layer that separates Urban out of the Non-remnant category)
4. I'd like to check how much area of each habitat type there actually is within the Brisbane LGA area. Some of them might be tiny (e.g. mixed or Acacia), and thus best dealt with by merging them into another one.
5. I'd also like to check you have the offshore boundary - will start another issue for this

**Comment by jeffreyhanson** [comment]
With regards to (4), here's a table showing the total/percent of land covered by each vegetation class inside the Brisbane extent (including Moreton Island):

|Name         |              Area| Percent|
|:-------------|-----------------:|----------:|
|Non-remnant   | 5637.2943558 km^2|     51.332|
|Estuary       | 2160.5791779 km^2|     19.674|
|Eucalypt      | 2045.9403442 km^2|     18.630|
|Ocean         |  312.8977243 km^2|      2.849|
|Mixed         |  216.2268195 km^2|      1.969|
|Water         |  171.9134176 km^2|      1.565|
|Mangroves     |  155.4628873 km^2|      1.416|
|Rainforest    |  117.5903875 km^2|      1.071|
|Melaleuca     |  104.5762959 km^2|      0.952|
|Wetlands      |   55.7134281 km^2|      0.507|
|Acacia        |    3.8122906 km^2|      0.035|
|Small-remnant |    0.0971786 km^2|      0.001|

**Comment by jeffreyhanson** [comment]
Just in case this issue has become buried, @dbl3raf it would be great if you could confirm (1) which vegetation classes should be merged together and (2) which data set you would like to use for delineating urban areas? For (2) we could use remotely sensed data (e.g. MODIS) or vector data distributed by the QLD government (e.g. http://qldspatial.information.qld.gov.au/catalogue/custom/detail.page?fid={063A413F-7910-4E6B-8389-24E06AF4508C})

**Comment by dbl3raf** [comment]
@jeffreyhanson - awesome find! If you could use the "Built up areas - Queensland" dataset you link above to divide the non-remnant category into "Non-remnant" and "Urban" that would be brilliant. Could you please send me the final shapefile so I can put it on record? Worth doing the GIS work within a broad buffer around the LGA just in case we need a wider extent at some point in the future for something.

**Comment by jeffreyhanson** [comment]
@dbl3raf, can you create a list showing which categories should be grouped together and what names these categories should be given?

**Comment by dbl3raf** [comment]
[Atlas Habitats.xlsx](https://github.com/bird-team/brisbane-bird-atlas/files/2077952/Atlas.Habitats.xlsx)

Here's a spreadsheet that ultimately results in 9 mapped habitat categories. It uses the data in DBVG5M where they exist, and then DBVG1M when the DBVG5M field is blank. I can work on shortening some of the names if there is trouble fitting them onto the graphs.

Looking carefully at the non-rem category, you will see I have split it into three: Built-up, Urban green space, Wetland - I hope there's a way to use the land use mapping to achieve this three-way split. Let me know if that proves tricky. Also let me know if you prefer me to do the GIS for this - for efficiency's sake I'm keen to have you focus on the stuff you are uniquely qualified to do.

**Comment by jeffreyhanson** [comment]
Ok - no worries - I can do this. Would this data set be sufficient for delineating wet lands?

https://data.qld.gov.au/dataset/wetland-data-version-4-queensland-series

**Comment by dbl3raf** [comment]
That's perfect - nice layer!

**Comment by jeffreyhanson** [comment]
I've processed the environmental data following the spreadsheet and using the previously discussed methods. I've attached a zip-file with the data ([data.zip](https://github.com/bird-team/brisbane-bird-atlas/files/2096630/data.zip)), and included a table below showing the total area of each habitat class and it's area expressed as a percentage of the total in the data set. 

I find it strange that so much area is assigned to the Urban Green Space class and so little area is assigned to the Built up class. The reason for this is because non-remnant areas in the data set do not overlap with the wetland or the urban data (i.e. http://qldspatial.information.qld.gov.au/catalogue/custom/detail.page?fid={063A413F-7910-4E6B-8389-24E06AF4508C), so they get allocated to the Urban Green Space class by default. What do you think? 

|atlas_name        |           area| percentage|
|:-----------------|--------------:|----------:|
|Rainforest        |   76587640 m^2|   1.101134|
|Wet sclerophyll   |   91585198 m^2|   1.316761|
|Dry woodland      | 1259539850 m^2|  18.108956|
|Coastal heath     |  165412874 m^2|   2.378213|
|Urban Green Space | 2744223132 m^2|  39.454897|
|Built-up          |  101826202 m^2|   1.464000|
|Wetland           |  205223552 m^2|   2.950589|
|Estuary           | 2194612003 m^2|  31.552897|
|Ocean             |  116331820 m^2|   1.672554|

If you're happy with this data set though, let me know and I can integrate it into the atlas.

**Comment by jeffreyhanson** [comment]
Hmm, I'm looking over the code and I think there might be something strange going on, let me double check if it's working correctly.

**Comment by jeffreyhanson** [comment]
It looks like I accidentally oversimplified the urban data during processing, I'll run it again and upload another shapefile + data

**Comment by jeffreyhanson** [comment]
Ok, here's the correct version of the habitat data ([exports.zip](https://github.com/bird-team/brisbane-bird-atlas/files/2097723/exports.zip)) and the extent of each class. What do you think?

|atlas_name        |           area|      prop|
|:-----------------|--------------:|---------:|
|Rainforest        |   76587640 m^2|  1.101135|
|Wet sclerophyll   |   91585198 m^2|  1.316761|
|Dry woodland      | 1259539850 m^2| 18.108967|
|Coastal heath     |  165412874 m^2|  2.378215|
|Urban Green Space | 1896188294 m^2| 27.262346|
|Built-up          |  807016609 m^2| 11.602838|
|Wetland           |  348063666 m^2|  5.004267|
|Estuary           | 2194612003 m^2| 31.552917|
|Ocean             |  116331820 m^2|  1.672554|

**Comment by dbl3raf** [comment]
looks great @jeffreyhanson, couple of small points:

1. The urban polygons are rather simplified, but I guess that's how they are in their native resolution? No dramas if that's how they are - I just thought I'd check.
![image](https://user-images.githubusercontent.com/23551540/41347254-686fd28c-6f4c-11e8-810d-15cb43f5e2ee.png)

2. Let's change the following names:

"Coastal heath" to "Heath"
"Urban Green Space" to "Non-remnant" (since much of it is well beyond the city)

Then all good to go - the mapping looks great!

**Comment by jeffreyhanson** [comment]
I've just double checked and yeah the urban polygons are rather simplified, but that's due to the resolution of the original data set.

Ok, I'll rename the classes and update the data set in the atlas.

**Comment by dbl3raf** [comment]
Awesome Jeff - consider buffering the extent of this habitat dataset beyond the LGA boundary to allow for a bit of wiggle room (e.g. squares that extend beyond boundary etc)

**Comment by jeffreyhanson** [comment]
Yeah that's a good idea, I'm rerunning it with a 20 km buffer - do you think that's sufficient?

**Comment by dbl3raf** [comment]
sounds plenty to me

**Comment by jeffreyhanson** [comment]
ok, for some reason it was taking ages to process with a 20 km buffer, so I've run it with a 5 km buffer and updated the atlas. I'll close this issue now.
