### ISSUE TITLE
DEM data below sea level

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#19]
Jeff - presumably there is a DEM raster that you're using for the elevation analysis? Does it have negative values (i.e. below sea level). If so, these should all be updated to zero, to avoid funny results in the elevation graphs. I noticed this when I was playing with eastern curlew last night.

**Comment by jeffreyhanson** [comment]
Yeah the DEM raster has some cells with negative values. Sure, can do.

**Comment by dbl3raf** [comment]
great, thanks @jeffreyhanson
