### ISSUE TITLE
Interactive graphs

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#20]
It looks like we could use _plotly_ to include interactive graphs (https://plot.ly/r/) on the online version of the atlas. Although since we're mainly using histograms (https://plot.ly/r/histograms/) and box plots (https://plot.ly/r/box-plots/), maybe there won't be much benefit? I think if there was some way to link this with the interactive map then that might be cool (e.g. select range of years on the histogram and it only shows the points on the map)? Thoughts?

**Comment by dbl3raf** [comment]
At this point I think I agree with your first conclusion, that we are using simple plots and I don't see a big benefit of interactivity; the central purpose of the atlas is to present synthesised information (together with interpretation via the text) rather than be a data mining tool

**Comment by jeffreyhanson** [comment]
Ok, yeah, I agree. I'll close this for now then, if you have any ideas for making interactive graphs please feel free to reopen this issue and we can chat more about it.
