### ISSUE TITLE
Book cover

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#21]
It might be nice to have a cover for the offline pdf version of the book. What do you think @dbl3raf?

**Comment by dbl3raf** [comment]
I agree @jeffreyhanson - I'll need to find an arty / design person who can help

**Comment by jeffreyhanson** [comment]
Ok, I'll set up the pdf template to source an image for the cover page, so when the cover is ready, we would only need to copy in the image.

**Comment by jeffreyhanson** [comment]
Ok, I've created a temporary cover and have included it in the book, so we can close this for now.
