### ISSUE TITLE
Offshore records

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#22]
See attached kml file that has been changed to .txt
[BNE_offshore.txt](https://github.com/bird-team/brisbane-bird-atlas/files/2042999/BNE_offshore.txt)

We need somehow to capture offshore records when we sweep the eBird dataset

We need a strategy for whether / how to map the offshore environment. Two issues:

1. mudflat hotspots can appear just offshore and might be missed by the grid square system we currently have. Need to investigate whether this is happening, and perhaps extend the grid squares further out.

2. Offshore records (eg. https://ebird.org/australia/view/checklist/S46058992) need to be captured somehow, but we need to decide the best way of doing this, e.g. whether it is by formal extension of the 2km square mapping, or whether it is done in a more qualitative way, e.g. by keeping the terrestrial squares more or less as they are, and just using the marine records to populate graphs etc. Some discussion needed on this one.

**Comment by jeffreyhanson** [comment]
I feel like it might be confusing for readers if the maps just use terrestrial data and the the graphs use terrestrial + marine data. What if we tagged each species as "terrestrial" or "marine"? If terrestrial, then the maps just show the Brisbane area and the graphs also correspond to Brisbane. If marine, then the maps use the attached kml as the "study area" and show Brisbane and the offshore areas, and the graphs use all records found inside the kml? Though the grids might need a coarser resolution when including offshore areas (e.g. 10 km)?

**Comment by jeffreyhanson** [comment]
10 km grid for seabirds
include column in spreadsheet to tag species as offshore or Brisbane
@dbl3raf, make a shapefile covering offshore area + Brisbane with 2km grid, centred around Oxley Creek Commons

**Comment by dbl3raf** [comment]
I'm still working on this - sorry for delay

**Comment by dbl3raf** [comment]
I confess I'm struggling with the GIS - I'll try and catch you in the corridor. Tricky bit is creating an offshore polygon of the Brisbane LGA boundary. See https://www.fullerlab.org/feb-4-rr-gis/ - I did it by joining a 1km grid of points to the LGA layer, but I wonder if there is a GIS process that will make a polygon enclosing the entire offshore area that is closer to Brisbane LGA than any other LGA.

**Comment by jeffreyhanson** [comment]
I'm home sick today, but we could skype or try catching up tomorrow. Yeah, I agree, I think creating such a layer is tricky, it might be easier to just draw the offshore polygon and then merge with the Brisbane LGA?

**Comment by dbl3raf** [comment]
tricky bit is drawing it? I'm doing a 1 km grid of points at the moment, but the spatial join is taking absolutely ages - will be about a week at this rate, providing it doesn't crash

**Comment by dbl3raf** [comment]
well the spatial join finished, and here is the resulting 2km grid, with a field land to indicate whether a grid cell intersects with land or not. It looks ugly on the eastern pelagic border, because of the shape of the EEZ. If this is annoying for the mapping, I can tidy it up.

As a reminder, we were going to show just the land cells as a default for the majority of species.

[atlas2kgridv01.zip](https://github.com/bird-team/brisbane-bird-atlas/files/2108907/atlas2kgridv01.zip)

**Comment by jeffreyhanson** [comment]
Ok great. The zipfile doesn't contain a .prj file - what coordinate system is the shapefile in?

**Comment by dbl3raf** [comment]
World Behrmann

**Comment by jeffreyhanson** [comment]
Ok - the interactive map requires web Mercator (https://epsg.io/3857), so I'll remake the grid in that coordinate system, and intersect it with your grid to extract desired cells + assign land data.
