### ISSUE TITLE
Bird calls?

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#23]
I stumbled across this website which has community submitted bird calls (https://www.xeno-canto.org). If you like we could try embedding them in the species' pages (e.g. https://www.xeno-canto.org/species/Dendrocygna-arcuata?view=3)? It looks like the recordings are licensed under CC BY-NC-ND 4.0 (https://creativecommons.org/licenses/by-nc-nd/4.0/), so we would only need to provide attribution to use them (assuming the atlas is remains non-commercial).

**Comment by dbl3raf** [comment]
@jeffreyhanson that's a BRILLIANT idea, let's do it. Can provide some sort of holder for several calls for each species? Would it be easier for you if the number of links was the same for each species, or could we easily have a variable number of calls embedded among species?

**Comment by jeffreyhanson** [comment]
Yeah, we could have a spreadsheet that stores the file paths/urls for the audio files and associates them with each species. For example, it could have a "species_scientific_name" column and a "audio_path" column. If a species is associated with multiple audio files, then it gets multiple rows. If a species is not associated with any audio files then it doesn't get a audio player widget on its page. How does that work?

**Comment by dbl3raf** [comment]
sounds completely awesome to me - would there be any way to easily embed Macaulay library calls as well (e.g. https://macaulaylibrary.org/asset/101095641?__hstc=60209138.78a85b5687f4f2ade165f93192172cfb.1523014213924.1527535661661.1527549716152.112&__hssc=60209138.2.1527549716152&__hsfp=127241091), or is a mixture too tricky? All the eBird recordings (e.g. https://ebird.org/australia/view/checklist/S45830817) get stored on Macaulay library

**Comment by jeffreyhanson** [comment]
The Macaulay library lets you embed the player in other websites, but if we wanted to include the call in a web player that let's people listen to multiple tracks (e.g. something like this: http://static.dymio.net/player-56s/demo/), then we would need the actual mp3 file. I'll see what I can do.

**Comment by jeffreyhanson** [comment]
Ok, I've added some audio functionality (see here for an example using recordings from the Macaulay library http://xenu-cantu.org: http://brisbanebirds.com/magpie-goose-anseranas-semipalmata.html). Behind the scenes, the book is reading the recording urls and metadata from the `data/audio/audio.xlsx` spreadsheet and using this information to populate the audio players. Let me know if you'd prefer a more minimal audio player (e.g. just a button), but bear in mind that we would need to display the recording author's name + recording origin + license info somewhere on the player.

**Comment by dbl3raf** [comment]
I think it looks totally brilliant Jeff - and if this is all easily updated via the spreadsheet, then that's ideal.

**Comment by dbl3raf** [comment]
no need for a more minimal player I don't think

**Comment by dbl3raf** [comment]
I guess we can close this one now?
