### ISSUE TITLE
Table of contents for online version

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#24]
How should the table of contents be styled for the html version? Specifically, do we want numbered sections? Should the bird entries be grouped as sub-headings under a main heading (currently species entries are grouped under a "Birds" heading), or should each bird header have the same format as other main headings in the book?

**Comment by dbl3raf** [comment]
No numbering for sections, but I do think we need more introductory sections - something like:

Preface
Introduction
Brisbane's Environment
Methods
Species Accounts
References
Acknowledgements
Gazetteer

**Comment by jeffreyhanson** [comment]
Done.

**Comment by jeffreyhanson** [comment]
Just to double check, you don't want the acknowledgements in the preface before the introduction?

**Comment by jeffreyhanson** [comment]
I've been working on the pdf templates, can you let me know what you think of (1) the table of contents formatting, (2) the order of the sections, and (3) how the sections are allocated to the front matter (denoted by roman numerals), main matter (denoted by regular numbers), and back matter (denoted by more roman numerals)? The pdf verison of the book can be found here: https://github.com/bird-team/brisbane-bird-atlas/raw/gh-pages/brisbane-bird-atlas.pdf

**Comment by dbl3raf** [comment]
This is perfect Jeff on all three of the questions you raise above.  Happy to go ahead with this organisation and TOC format. The cover design is really great - did you cut out the shoebill, or import the whole thing from somewhere else?

**Comment by jeffreyhanson** [comment]
Ok great, I'll close this issue then. Nah, I just used the O'rly parody book cover generator (https://dev.to/rly), it lets you create book covers using Wiley's format (e.g. https://www.google.com.au/search?tbm=isch&q=o%27rly+book+cover&spell=1&sa=X&ved=0ahUKEwiUr7Km2bPbAhWIEbwKHZf6AfAQBQg-KAA&biw=1280&bih=617&dpr=2.5).
