### ISSUE TITLE
Contributing document

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#3]

**Comment by jeffreyhanson** [comment]
The book version should have this placed in the front matter and this should be written for a general audience (and placed after Methods section), and create an online wiki page with the technical details for @dbl3raf

**Comment by dbl3raf** [comment]
Note there are two forms of contributing - in the field, and at the desktop. Probably both belong in this section

**Comment by dbl3raf** [comment]
on this issue - so we already have the online wiki now right? Is it just waiting for the contributing page to be added to the PDF version?

**Comment by jeffreyhanson** [comment]
Yeah, we have the wiki - and I think it's pretty much done for the moment. I'm sure new things will inevitably crop up and need to be added to the wiki, but for the moment I think it's complete? I'm not really sure what  should be added to the contributing section in the actual book - but I feel like it needs something. 

Maybe some instructions on how to edit a page, submit a pull request, and then an overview of what happens next (e.g. reviewed by admins, and then merged if desired?)? What audience should this be written for? I feel like the wiki is really good for admins or low level details, but maybe something written for the first time contributer (and GitHub user) would be better in the book?

**Comment by jeffreyhanson** [comment]
For inspiration, here's some contributing pages from other bookdown projects:
* https://github.com/hadley/r4ds/blob/master/contribute.rmd
* https://geocompr.robinlovelace.net/index.html#how-to-contribute

**Comment by dbl3raf** [comment]
thanks Jeff - I'll have a think and maybe write some initial starter text to fill this bit, and then we can close out this issue

**Comment by dbl3raf** [comment]
@Louis-Backstrom wrote some text, looks great for now - we can build it up as time goes by
