### ISSUE TITLE
Maps for online version

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#33]
I have some small design changes for the online maps - is now a good time to get them? Happy to wait until down the track, especially if some things might change as development progresses.

**Comment by jeffreyhanson** [comment]
Sure, list the design changes here and I'll get to them when I can.

**Comment by dbl3raf** [comment]
1. Colour ramp should be Reporting rate, in % rather than proportion
2. Colour ramp should be inverted, so 0% is at the bottom and 100% at the top
3. The Brisbane extent seems to have a very coarse boundary, and is missing, e.g. the three Bay islands - Mud, Green and St Helena
4. Would be good to have a radio button for all records, as well as the four seasons, if possible
5. I don't think the checklists and observations buttons have much utility? They seem to bring up circles with numbers in on the map, which just seem a bit confusing to me? I think we should stick with just the map, unless there's a compelling argument for have those extra buttons.
6. The buttons to zoom in and out in the top left hand corner don't always appear properly for me (Firefox) - this is probably just minor debugging that we can worry about later, unless anything obvious springs to mind
7. Make the buttons to zoom in and out in the top left hand corner a bit more obvious, e.g. bold white instead of blue
8. As in the static PDF maps, we need to ensure to distinguish zero reporting rate from no checklists in a grid cell. I think the existing setup already achieves this since a RR of 0 will have a dark purple shade whereas a cell with no checklists will appear totally transparent? To consider and check.

**Comment by jeffreyhanson** [comment]
I've done some work on the online interactive maps, can you take a look @dbl3raf ? I think I've addressed all your suggestions, except for the one pertaining to the precision and completeness of the Brisbane footprint polygon which I've moved to its own issue (#34)? I've double checked with firefox and the zoom buttons appear and work for me.

**Comment by dbl3raf** [comment]
Brilliant - all looks good, noting that the higher resolution boundary is now part of another issue.

The only tweak missing was:

**5. I don't think the checklists and observations buttons have much utility? They seem to bring up circles with numbers in on the map, which just seem a bit confusing to me? I think we should stick with just the map, unless there's a compelling argument for have those extra buttons.**
