### ISSUE TITLE
Brisbane study area extent

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#34]
The current Brisbane extent shapefile is too coarse and is missing the three Bay islands (Mud, Green and St Helena). This issue was originally raised in #33, but has been moved to its own issue because this pertains to the underlying data of the atlas.

**Comment by jeffreyhanson** [comment]
@dbl3raf, in #33 you say that the Brisbane poylgon is too coarse and is missing several islands. Can you  please confirm if these issues are also a problem for the offline maps in the pdf version of book? If so, shall I create a new higher resolution shapefile to use for both the offline and online versions of the map? Alternatively, if you want the offline map to stay as it currently is, should I use only the new higher resolution shapefile for the online version of the map?

**Comment by dbl3raf** [comment]
The maps in the PDF version are also noticeably low resolution and also missing the three Bay Islands, so the higher resolution shapefile needs to apply throughout

**Comment by dbl3raf** [comment]
this one seems to be the best for LGA extent: http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1270.0.55.003July%202016?OpenDocument and choose document "Local Government Areas ASGS Ed 2016 Digital Boundaries in ESRI Shapefile Format"
