### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#35]
Create a wiki that details the structure of the atlas and methods for manipulating it.

**Comment by jeffreyhanson** [comment]
@dbl3raf, I've added all the FAQS, can you please take a look at the wiki (https://github.com/bird-team/brisbane-bird-atlas/wiki) and see if you think it is missing anything or any details are insufficient?

**Comment by dbl3raf** [comment]
As discussed yesterday I think this covers everything, so I'll close the issue. If other things come up, we can re-open or create a new issue.
