### ISSUE TITLE
New graph type: monthly breeding activity

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#36]
I hesitate to propose this, but after thinking about it for a while, I'm really keen for it if possible.

A graph showing breeding activity by month. So it would be a "reporting rate" statistic. The proportion of all records of, e.g. magpie goose in which breeding activity was observed, plotted by month. So, if there were 64 observations of magpie goose in January, and 32 of them had breeding activity recorded for them, the breeding reporting rate would be 50%.

Breeding activity is stored in the BREEDING_BIRD_ATLAS_CODE field, and I consider the following to be indicative of confirmed breeding activity:

NY
NE
ON
FL
FY
NB

If this is too time-consuming, let me know.

I'm also aware that it raises the number of graphs to five, which is awkward. Happy to discuss this more.

**Comment by jeffreyhanson** [comment]
Sure, I don't think this graph would take too long to make. Yeah it does bring the graph count to 5, so if you have any ideas for dropping one of the other graphs or adding a new graph let me know.

**Comment by jeffreyhanson** [comment]
@dbl3raf can you please confirm if by "all records" you indeed mean "all records" or "true checklists"?

**Comment by dbl3raf** [comment]
all records, even if they are collected as part of a non-complete checklist

**Comment by jeffreyhanson** [comment]
Ok. With the version of the data you gave me last week, only 2290 records meet this criteria (< 1% of the data), so I expect the proportions will be very low for most species across all months. I'll have a graph to show in a few minutes.

**Comment by dbl3raf** [comment]
I'm probably OK with that - in part this is going to show that we need to amass much more information on breeding

**Comment by dbl3raf** [comment]
> Yeah it does bring the graph count to 5, so if you have any ideas for dropping one of the other graphs or adding a new graph let me know.

Since most species would have all five graphs that we are currently considering, I agree it might be nice to add a sixth - all six would then form the default layout. 

The major piece we are missing from the atlas so far is something on abundance. There isn't an easy way to represent abundance without modelling it, but I was wondering if we could do a box plot just like the elevation plot, but for the field OBSERVATION_COUNT - so have a monthly graph showing variation in count (this would include all records, not just complete checklists). So long as there isn't systematic monthly variation in checklist durations or distances walked, the numbers would be broadly comparable, and would complement the monthly reporting rate graph nicely.

If this is possible, I think we should have the six graphs appear in the order Habitat, Elevation, Monthly reporting rate, Monthly counts, Monthly breeding, Annual reporting rate

**Comment by jeffreyhanson** [comment]
Ok sounds good. Here's what the five panel graphs with the breeding rate graph are looking like:

![anseranas-semipalmata](https://user-images.githubusercontent.com/3610005/41274071-5de3ed8c-6e5f-11e8-82b0-433a25cf678c.png)

I'll start on the abundance graph, and post a six panel graph to see what you think.

**Comment by dbl3raf** [comment]
awesome @jeffreyhanson! the habitat graph still has the old categories right?

**Comment by jeffreyhanson** [comment]
Yeah, I'm still working on the habitat data.

**Comment by dbl3raf** [comment]
no worries at all - just wondering. This is looking really good @jeffreyhanson, brilliant work

**Comment by jeffreyhanson** [comment]
Ok, here's the six panel figure with the count data. Are there any changes you'd like to it?

![anseranas-semipalmata](https://user-images.githubusercontent.com/3610005/41275304-ccb02826-6e63-11e8-9d63-0edc8e669b11.png)

**Comment by dbl3raf** [comment]
@jeffreyhanson this is simply amazing - great job. Everything is perfect content-wise, labelling-wise and layout-wise. My final wonder is whether the black bars on the habitat, monthly RR, breeding, and annual RR graphs might work better as open bars like those used in the elevation and count plots? .i.e. bars that are open, and with a small gap between them - if you can bear it, and if the code is straightforward I'd be really keen to see a quick grab of those to decide if it looks better. If the code is fiddly, no need to worry.

**Comment by jeffreyhanson** [comment]
Sure, that should be doable, I'll see what I can do.

**Comment by jeffreyhanson** [comment]
Ok, here's the graphs with a white fill and space between the bars. Which do you prefer?

![anseranas-semipalmata](https://user-images.githubusercontent.com/3610005/41288192-d338d024-6e88-11e8-8d0d-4c7f4c37dfe5.png)

**Comment by dbl3raf** [comment]
brilliant @jeffreyhanson I definitely prefer this - great job. Issue can be closed as far as I can see

**Comment by jeffreyhanson** [comment]
Ok great, I've just pushed the new code (forgot to tag the issue though), so I'll close this now.

**Comment by Louis-Backstrom** [comment]
Just a thought regarding what we consider to be confirmed breeding - the eBird dataset has a second column "BREEDING BIRD ATLAS CATEGORY" that I think would make life somewhat easier if we used it. C4 basically contains everything that's either confirmed or probable - everything on this [list](https://help.ebird.org/customer/portal/articles/1006850-breeding-codes-behavior-codes) down to PE (or maybe B, but that isn't used in Australia). I think this would get us more data but not necessarily worse data, and it's also much easier to sort back end for just C4 records when doing accounts, rather than trying to add in each of the specific ones we've got at the moment.

Thoughts @dbl3raf? I'm assuming this is a quick change in the parameters file @jeffreyhanson?

**Comment by dbl3raf** [comment]
@Louis-Backstrom can you find any documentation as to how the Atlas category codes are interpreted, and what the definition of the four different codes is? My gut feeling is that the current set up gives us full control over exactly which codes entered by the observer are used, and we can easily edit this list in the parameters file. If we wanted to add more breeding codes to exactly emulate C4, I would be happy with that, but maybe we should just do that, rather than seek a change to the field used, which needs programming time from @jeffreyhanson?

**Comment by Louis-Backstrom** [comment]
I couldn't through a brief search, no - I'd have to assume though that it exists somewhere.

I'd be more than happy to change the specific codes to match C4, that seems probably an even better solution as as you say we get full control

**Comment by Louis-Backstrom** [comment]
I've gone though and changed the parameters file to have all 12 "confirmed" codes as documented on eBird - the change should show up in the graphs after a rebuild of the assets.

**Comment by Louis-Backstrom** [comment]
I _believe_ this is fixed, but it's actually quite hard to be sure without being able to compare between the graphs before and after the change. I think it's good though, so I'll close it.
