### ISSUE TITLE
Acknowledge Birds Queensland

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#38]
As we discussed earlier, it would be good to acknowledge Birds Queensland and place their logo in the book (and also the README for the GitHu repo?). Where would you like this to be placed? Should we use the color or black and white version of the logo?

![](https://www.birdsqueensland.org.au/images/Logo_small.gif)
![](https://c8.staticflickr.com/8/7251/26604214703_80d8a0d44c_o.jpg)

**Comment by dbl3raf** [comment]
Great - on the preface page, below the date. Colour version please. And with the text "Generously supported by Birds Queensland" underneath.

**Comment by jeffreyhanson** [comment]
Done.
