### ISSUE TITLE
May 2018 data update

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#39]
Fresh update just out of eBird - these are all the records from the Brisbane LGA as per eBird. So we don't need to spatially clip them. Once we have the terrestrial grid squares organised, I'd be keen to get a list of all locations that fall outside them, so I can reposition or invalidate them within eBird if they are intended to be terrestrial locations.

https://www.dropbox.com/s/tmeedeo23zyfrs0/ebd_AU-QLD-BRI_relMay-2018.zip?dl=0

**Comment by dbl3raf** [comment]
worth looking at the metadata file - there are quite a few changes since last time

**Comment by jeffreyhanson** [comment]
Ok can do. 


Also, at the moment, all the graph and maps omit records that are not collected from a complete year (so any records from 2018 are discarded). Can you please confirm which graphs and maps should use records only from complete years vs. all years after 2005? I've listed the graphs and maps below, if you could please put a yes/no next to each one I can update them.

* graphs:
  -  reporting rate by vegetation: CAN USE INCOMPLETE YEARS
  -  reporting rate by year: COMPLETE YEARS ONLY
  -  reporting rate by elevation: CAN USE INCOMPLETE YEARS
  -  reporting rate by month: COMPLETE YEARS ONLY
  -  breeding rate by month: COMPLETE YEARS ONLY
   - count by month: CAN USE INCOMPLETE YEARS

* maps:
  - autumn: COMPLETE YEARS ONLY
  - winter: COMPLETE YEARS ONLY
  - summer: COMPLETE YEARS ONLY
  - spring: COMPLETE YEARS ONLY
 -  total records (#42): CAN USE INCOMPLETE YEARS

**Comment by jeffreyhanson** [comment]
Brilliant - thanks!
