### ISSUE TITLE
Map of records across whole year

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#42]
We need a fifth map, which is all records over the whole year. This can be added as a radio button on the online version, and be added to the palette of possible maps for the PDF version (although in an annoying echo of the graphs situation, that makes for five maps for a highly seasonal species)

**Comment by jeffreyhanson** [comment]
@dbl3raf, can you please clarify if you want the map to show reporting rate or the total number of records?

**Comment by jeffreyhanson** [comment]
I've created the maps using the reporting rates so I'll close this now, but please reopen this issue if it should be the total number of records instead.
