### ISSUE TITLE
Moreton Bay Shire data

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#43]
@dbl3raf, as we discussed this morning, could you please send me a copy of the eBird data for the Moreton Bay Shire LGA?

**Comment by dbl3raf** [comment]
I'm still waiting for the download link from eBird - I presume this is now super urgent?

**Comment by dbl3raf** [comment]
I can do a world download immediately, but it's 25GB and might get a bit messy manipulating the file?

**Comment by jeffreyhanson** [comment]
Thanks for the offer. Richard's happy with the Brisbane extent, if we can get the Moreton Bay Shire than that's brilliant, but it's not needed. So, if the download link for the Moreton Bay Shire manifests sometime tomorrow it would be great if you could send me the data, but otherwise I don't think it's worth the hassle of working with the full database.

**Comment by dbl3raf** [comment]
OK, understood. Still no sign of it this morning.

**Comment by dbl3raf** [comment]
it never came - closing issue
