### ISSUE TITLE
Threshold number of checklists for calcuation of reporting rates

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#44]
To follow up on something we discussed today, I'd like to have the ability to set a threshold for the number of checklists required in a cell before permitting a reporting rate to be calculated, e.g. maybe there should be at least three complete checklists before calculation of reporting rate is allowed for a cell. But the ability for me to edit this parameter in the future would be really useful.

**Comment by jeffreyhanson** [comment]
This is handled by the "minimum_required_checklists" parameter in the file "data/parameters/parameters.yaml". It is currently set at 5. If you would like to try a different value, please open a new issue.
