### ISSUE TITLE
Tweak initial map extent

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#46]
Not sure how customizable this is, but I wonder if the online map could open with an initial extent something like the following, so that it emphasizes mainland Brisbane more - users can obviously pan around if they are particularly interested in Moreton Island.
![capture](https://user-images.githubusercontent.com/23551540/41712917-193f00a4-758f-11e8-87b6-8b92f841b4e4.JPG)

**Comment by jeffreyhanson** [comment]
Yeah that's doable.
