### ISSUE TITLE
Getting ready for sharing the prototype atlas

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#48]
I want to start sharing the prototype atlas link with a few carefully selected folks who can usefully comment on content and presentation issues. As I've mentioned, I'll control this process tightly, so refer any comments to me. A few small tweaks / questions as we get ready for this:

1. let's remove our names from the title page at https://brisbanebirds.com/index.html.
2. Is it relatively easy to auto-create the entire atlas to the stage that the magpie goose account is at? I'm assuming if we auto-create it with lorem ipsum text, we can just as easily write over that if we make further major design tweaks?
3. As default we can set it for all graphs and maps to appear for all species.

**Comment by jeffreyhanson** [comment]
Sure. Before we do this, personally, I think it would probably be good to make sure any outstanding issues that affect the atlas style or content are addressed. Specifically, I think the following issues should be addressed before this one: #22, #38, and #47. What do you think?

**Comment by dbl3raf** [comment]
Good point. Happy to address those issues first. The reality is that when I start sharing this, there will be a swag of further adjustments to make. Hopefully we'll be able to contain them to fairly minor adjustments. The alternative is that I come up with a short list of species that exemplify the full range of variation in types of distribution / abundance? This might help us road test it a little harder before seeking external input

**Comment by jeffreyhanson** [comment]
Personally, I like the short list idea. I think this will make it easier to solicit specific feedback from other individuals because it means they won't have to look through 300+ species in order to appreciate all the "combinations" of different settings/types. Could you please put together a short list from this spreadsheet ([atlas_list.xlsx](https://github.com/bird-team/brisbane-bird-atlas/files/2135835/atlas_list.xlsx))? You could just delete the rows for species that should not be in the short list.

**Comment by dbl3raf** [comment]
We decided on keeping the full list, but I've added all the threat statuses, and some species that should show both marine and terrestrial maps. Once I see the all the graphs and maps, I'll have one final play with which ones should display for each species before sending the prototype out for comment.
[atlas_list.xlsx](https://github.com/bird-team/brisbane-bird-atlas/files/2142872/atlas_list.xlsx)

**Comment by dbl3raf** [comment]
From what I can see, I think we are essentially ready for the full run of all species. I'm off on holiday on Thursday and would be massively keen to get the link circulated before then, so people can look while I'm away with a strict 1-week deadline. I'll then collate comments, and boil them down into a set of issues that I can put up, for a final push towards the first full draft. We can then start test the functionality for writing species accounts. I'd like to roll out the community contribution side of this on 1 August, ahead of a talk I'm doing at Birds Queensland in early September (so we can it debugged).

**Comment by jeffreyhanson** [comment]
Yeah, that sounds like a good plan. I'll let you know once I've addressed #58 and #55, and added pages for all the birds to the atlas.

**Comment by dbl3raf** [comment]
brilliant Jeff - I really appreciate everything you're doing on this. There is huge interest in the birding community, and I've already shown it to some Qld government folks, who think it is utterly amazing and useful. I'll also approach Brisbane City Council once we have a working prototype.

**Comment by jeffreyhanson** [comment]
Sorry for the late reply, I just noticed that I hadn't replied to this. No worries at all, it's great to hear that people are interested. Are there any remaining open issues or new issues that need to be resolved before it's ready for previewing for feedback?

**Comment by dbl3raf** [comment]
no, we are good to go. I'll start circulating the prototype as soon as I've got the magpie goose account looking good. If I have any questions on that I'll use the other thread. I'll close this issue.
