### ISSUE TITLE
Color ramp

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#55]
We need to decide on the best color ramp palette for the maps. Here is a website with some standardized color ramps for inspiration: http://colorbrewer2.org.

**Comment by dbl3raf** [comment]
I think greens (single hue) is the way to go - the color ramp brewer only goes up to 9 classes, but I think you said you could create a more continuous ramp. We will need to ensure that the grey colour chosen for the no data shading is distinguishable from all shades of the green, at least on screen. There will be no chance of this working for grayscale print-outs, but that is inevitable I think, whatever color ramp we choose.

**Comment by jeffreyhanson** [comment]
Ok sounds good. Yeah I can use use the colors to create a continuous ramp.

**Comment by dbl3raf** [comment]
Reopening - the light end of the green ramp is too light. I think the lightest colour should be #99d8c9 - its really important the viewer can distinguish low reporting rate from absence.

**Comment by jeffreyhanson** [comment]
I'm using the colors in the 9-class version of the Greens ramp for interpolation (http://colorbrewer2.org/#type=sequential&scheme=Greens&n=9). Which color should be the lightest color in the ramp (e.g. #a1d99b)?

**Comment by jeffreyhanson** [comment]
Also, let me know if you don't like the range of colors in the 9-class version and I can interpolate the colors using a different number-class version (e.g. the 5 class version but starting #74c476; http://colorbrewer2.org/#type=sequential&scheme=Greens&n=5).

**Comment by dbl3raf** [comment]
ok yep - the range of colours in the 5-class option is great. Starting at **#bae4b3** will be good I think - we want as broad a range of brightnesses as possible without the lighter end being hard to see.

**Comment by jeffreyhanson** [comment]
Ok, I've updated the color ramp, can you let me know what you think (e.g. https://brisbanebirds.com/magpie-goose-anseranas-semipalmata.html#magpie-goose-anseranas-semipalmata)?

**Comment by dbl3raf** [comment]
can the dark end be made darker? to 006d2c

**Comment by jeffreyhanson** [comment]
The color ramp goes to 006d2c at 100%, but the colors on the map don't go to 006d2c because the highest number is ~85% (and the reason the legend goes to 100% is to have "pretty" labels with equal increments). So, we could make it darker selecting a higher-class ramp (e.g. 7-class Greens; http://colorbrewer2.org/#type=sequential&scheme=Greens&n=7)? What do you think of 7-class Greens starting at #a1d99?

**Comment by dbl3raf** [comment]
yes - good idea, try that one

**Comment by jeffreyhanson** [comment]
Ok, the magpie goose maps with the 7-class starting Greens starting at #a1d99. What do you think?

![anseranas-semipalmata](https://user-images.githubusercontent.com/3610005/42200291-de5675d0-7ed5-11e8-9bcf-395522357cc4.png)

**Comment by dbl3raf** [comment]
looks great, nice one!

**Comment by jeffreyhanson** [comment]
Ok, I'll update the rest of the maps with this color ramp
