### ISSUE TITLE
Setup GitLab pushes for automated back-ups

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#56]

**Comment by jeffreyhanson** [comment]
@dbl3raf, I've created a group and repository on GitLab (https://gitlab.com/) to back up this GitHub repository, could you please create a user on GitLab and send me the username so I can grant you access to the GitLab repository?

**Comment by jeffreyhanson** [comment]
The atlas is now automatically backed up here (https://gitlab.com/bird-team/brisbane-bird-atlas-backup). Note that it is a private repository and so cannot be viewed without authorisation. @dbl3raf, once you send me your Gitlab username I can add you to the repository.

**Comment by dbl3raf** [comment]
my Gitlab username is dbl3raf

**Comment by jeffreyhanson** [comment]
Ok, I've added you to the GitLab "bird-team" group, so you should be able to access the backup repository.
