### ISSUE TITLE
Limit max on reporting rate color ramp to 100%

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#58]
the max on the color ramp legends on the maps often goes above 100% - can it be limited to 100%

**Comment by jeffreyhanson** [comment]
Thanks for catching that - can do.

**Comment by jeffreyhanson** [comment]
This was being caused by a bug in the reporting rate calculations rather than the plotting code. I'll push an update that fixes this, but expect the maps to change a bit with this new update.
