### ISSUE TITLE
Error processing assets for Calidris subminuta

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#60]
```
Error in ans[!test & ok] <- rep(no, length.out = length(ans))[!test &  : 
  replacement has length zero
Calls: vapply ... expand_range4 -> expand_range -> <Anonymous> -> f -> ifelse
In addition: Warning messages:
1: In max(x) : no non-missing arguments to max; returning -Inf
2: In rep(no, length.out = length(ans)) :
  'x' is NULL so the result will be NULL
```

**Comment by jeffreyhanson** [comment]
This species does not have any records collected during or after 2005 and not during 2018. This causes an error when attempting to make the breeding activity graph. @dbl3raf, should we (1) not make the breeding activity graph for this species, (2) not make any of the graphs for this species, or (3) change the minimum checklist and record years for this species?

**Comment by dbl3raf** [comment]
Change the minimum record year to 1700 I reckon.

**Comment by dbl3raf** [comment]
this will pick up the 1987 and 2004 records of this species
