### ISSUE TITLE
Species with zero records in 2005 and afterwards

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#61]
Thirty species in the spreadsheet have zero records collected during 2005 and afterwards (and excluding 2018). How should these species be treated in the atlas? Should the earliest record year be set to 1700 as in #60?

Below is a list of the species:

|species                     |
|:---------------------------|
|Haematopus finschi          |
|Pluvialis dominica          |
|Vanellus tricolor           |
|Tringa flavipes             |
|Stercorarius longicaudus    |
|Leucophaeus pipixcan        |
|Larus pacificus             |
|Oceanites oceanicus         |
|Pelagodroma marina          |
|Fregetta tropica            |
|Thalassarche chlororhynchos |
|Thalassarche melanophris    |
|Macronectes giganteus       |
|Fulmarus glacialoides       |
|Daption capense             |
|Pachyptila desolata         |
|Pachyptila belcheri         |
|Pterodroma solandri         |
|Pterodroma neglecta         |
|Ardenna carneipes           |
|Calonectris leucomelas      |
|Puffinus gavia              |
|Puffinus huttoni            |
|Sula leucogaster            |
|Dacelo leachii              |
|Lathamus discolor           |
|Lichenostomus melanops      |
|Coracina maxima             |
|Corvus coronoides           |
|Cheramoeca leucosterna      |

**Comment by jeffreyhanson** [comment]
It appears that even if we set the earliest record year to 1700 for these species, sixteen species will still not have any records. These are outlined in the table below. Should the atlas accommodate these species by not showing maps and graphs for them?

|species                  |
|:------------------------|
|Pluvialis dominica       |
|Stercorarius longicaudus |
|Oceanites oceanicus      |
|Pelagodroma marina       |
|Fregetta tropica         |
|Thalassarche melanophris |
|Macronectes giganteus    |
|Fulmarus glacialoides    |
|Daption capense          |
|Pachyptila desolata      |
|Pachyptila belcheri      |
|Pterodroma solandri      |
|Pterodroma neglecta      |
|Ardenna carneipes        |
|Calonectris leucomelas   |
|Lichenostomus melanops   |

**Comment by dbl3raf** [comment]
Most of these have records, but they are offshore only. It has recently emerged that the record for Lichenostomus melanops was invalid, and so it needs to be removed from the base list. Some others only have museum specimens etc and they haven't yet been added to eBird. Yes we can accommodate them by not showing maps and graphs.

**Comment by jeffreyhanson** [comment]
Ok will do.
