### ISSUE TITLE
Species with no finite "OBSERVATION COUNT" values

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#66]
The following 10 species do not have a single record with a finite (i.e. non-missing value) in the "OBSERVATION COUNT" column (excluding records before 2005; though even if we set this to 1700 then these species still have this problem). This means we cannot produce the boxplot showing monthly differences in observation counts for these species (since the code is attempting to make a graph using a table with zero rows).

@dbl3raf, how would you like to handle these species? We could change the atlas settings to exclude this particular graph (number 4) for these species? But then we would have 5 graphs for these species which may not look very nice.

|species                      |
|:----------------------------|
|Stiltia isabella             |
|Thalassarche chlororhynchos  |
|Puffinus gavia               |
|Sula leucogaster             |
|Dacelo leachii               |
|Climacteris picumnus         |
|Coracina maxima              |
|Artamus minor                |
|Motacilla alba               |
|Glossopsitta porphyrocephala |

**Comment by dbl3raf** [comment]
sure let's change the atlas settings to exclude the graphs that are throwing the error. A similar rule could apply to any further errors.

**Comment by jeffreyhanson** [comment]
Ok done.
