### ISSUE TITLE
Species with no complete checklists

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#67]
It appears that 27 species do not appear in any complete checklists after the 2005. However, the atlas is currently set to produce graphs for these species. How would you like to accommodate these species? We could keep the maps for these species but not show any of the graphs for these species? Or we could just not show the graphs that require complete checklists? 

| species name|
|:--------------------------------------------------------------|
|Haematopus finschi                                             |
|Vanellus tricolor                                              |
|Numenius minutus                                               |
|Calidris alba                                                  |
|Tringa flavipes                                                |
|Turnix pyrrhothorax                                            |
|Stiltia isabella                                               |
|Anous stolidus                                                 |
|Anous minutus                                                  |
|Leucophaeus pipixcan                                           |
|Larus pacificus                                                |
|Larus dominicanus                                              |
|Onychoprion fuscatus                                           |
|Thalassarche chlororhynchos                                    |
|Pterodroma leucoptera                                          |
|Puffinus gavia                                                 |
|Fregata ariel                                                  |
|Sula leucogaster                                               |
|Hamirostra melanosternon                                       |
|Dacelo leachii                                                 |
|Lathamus discolor                                              |
|Climacteris picumnus                                           |
|Coracina maxima                                                |
|Corvus coronoides                                              |
|Motacilla alba                                                 |
|Cheramoeca leucosterna                                         |
|Glossopsitta porphyrocephala                                   |

**Comment by jeffreyhanson** [comment]
If we set the starting checklist year to 1700 for these species, then this would still be a problem for the 19 species listed below.

| species |
|:--------------------------------------------------------------|
|Haematopus finschi                                             |
|Calidris alba                                                  |
|Turnix pyrrhothorax                                            |
|Anous stolidus                                                 |
|Anous minutus                                                  |
|Larus pacificus                                                |
|Larus dominicanus                                              |
|Onychoprion fuscatus                                           |
|Thalassarche chlororhynchos                                    |
|Pterodroma leucoptera                                          |
|Fregata ariel                                                  |
|Sula leucogaster                                               |
|Hamirostra melanosternon                                       |
|Dacelo leachii                                                 |
|Climacteris picumnus                                           |
|Coracina maxima                                                |
|Motacilla alba                                                 |
|Cheramoeca leucosterna                                         |
|Glossopsitta porphyrocephala                                   |

**Comment by jeffreyhanson** [comment]
I've updated the atlas to simply not produce graphs for these species. Let me know if you want to change this, otherwise we can close this issue.

**Comment by dbl3raf** [comment]
that's fine - thanks Jeff
