### ISSUE TITLE
Species checklist and record starting years

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#68]
I wonder if we should try embedding the species-specific checklist and record starting years into the figures? Or maybe we should have a programmatically generated caption for each figure that says this. I worry that having different "unknown" cells for different species might confuse some atlas contributors.

**Comment by dbl3raf** [comment]
I'm planning to use this feature incredibly sparingly, if at all. Just keen for it to be there if needed. As such, I reckon it's probably just as easy to mention any departure from the default in the textual species account.

**Comment by jeffreyhanson** [comment]
Ok sounds good. I'll close this issue then.
