### ISSUE TITLE
Builds timing out

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#69]
It looks like trying to build the atlas website is taking a very long time when we include all 300+ species, and so this causes the build service to terminate it. For previewing the atlas and getting feedback, it might be good to just show a select set of species while I work out how to reduce the build time (it doesn't look like this is something I can fix in easily). @dbl3raf, if you upload a copy of the `data/species/atlas_list.xlsx` file with the species you want to preview (ideally <50) then I can rebuild the atlas with just those species a temporary fix.

**Comment by dbl3raf** [comment]
[atlas_list_init.xlsx](https://github.com/bird-team/brisbane-bird-atlas/files/2192304/atlas_list_init.xlsx)

no worries - here is a cut-down list of 50 species

**Comment by jeffreyhanson** [comment]
I've added the file you uploaded to the atlas and the existing infrastructure has automatically rebuilt the offline and online versions of the atlas, so it looks like the existing infrastructure can handle the 50 species. I'll need to fix this issue before the atlas is "completely ready", but hopefully it will be sufficient for previewing the atlas when getting feedback on it. If not, let me know and I'll see what I can do, but this might mean that I have to make a lot of user visible changes that could take an extra week or two before the atlas is at a stage where it's ready for previewing again.

**Comment by dbl3raf** [comment]
this is brilliant - I'm happy to start sharing the atlas for feedback among the expert community now. I'll leave this issue open in case you want to use it to reference the long build time issue.

**Comment by dbl3raf** [comment]
Hi Jeff - I reckon this is the main issue to work on for the moment - trying to get the full atlas to build. I'm working on the survey sheets etc, but we might even end up going manual for that - not sure yet. But the build issue is something I can't fix myself, so should definitely be your highest priority in the time you have left I reckon

**Comment by jeffreyhanson** [comment]
Ok sounds good. I've managed to get the build time down to 21 minutes on my system with all 350+ species, but I'll try and address #71 and #72 before adding all the species to the online version so we don't run out of space on the GitHub repository.

**Comment by jeffreyhanson** [comment]
Also, I forgot to mention, since I'm making changes to the infrastructure of the atlas, can you please hold off on making any changes to the atlas until I've resolved this issue? This will make things easier for me to play around with the backend, without having to worry about integrating these changes with other changes too.

**Comment by dbl3raf** [comment]
no worries Jeff, that's totally fine

**Comment by dbl3raf** [comment]
If there's any chance of creating a build with all species in the next day or two that would be amazing - one of the senior managers at Brisbane City Council is interested in taking a look at the atlas

**Comment by jeffreyhanson** [comment]
Ok, I'm hoping that I'll have at least the website working by the end of today. It looks like the "website version" and the "pdf document version" have different system/environmental requirements (e.g. in terms of RAM and maximum allowable build time) which is making things tricky when trying to find a free service to make them.

**Comment by jeffreyhanson** [comment]
I've managed to get the website building now with all species. I'm still have trouble with the pdf document though because it requires a lot of RAM to build.

**Comment by jeffreyhanson** [comment]
I've managed to get the automated builds working for the website and offline pdf version - so I'll close this now.
