### ISSUE TITLE
Can I edit the Magpie Goose species account?

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#70]
Jeff - can I edit the account for magpie goose, so as to make a complete mock-up for that species account? I'm aware the work will be wasted if we write over it again, but it doesn't really matter - it's just a copy and paste job. I'll also need to add in some references etc, but I can easily see the field codes and referencing conventions, so I should be fine doing it.

If we do this, we'll need to compile it again for the 50 species - would that take too long? Or can you just recompile the one species?

**Comment by jeffreyhanson** [comment]
Yeah go ahead. Currently, the infrastructure supporting the atlas can support 50 species pretty easily. If you edit the magpie goose file then it should automatically rebuild the offline and online versions of the atlas.

**Comment by dbl3raf** [comment]
can I edit the references.bib file to add some new references?

And can I add a photo of magpie goose? I can't work out where the photos are / will be stored?

**Comment by jeffreyhanson** [comment]
Yeah, just make sure to follow the right format when editing references.bib (e.g. braces, quotes, commas, field names, etc). With regards to the photos, you could put it in the assets/profile folder for the time being if it isn't too large (<15 MB). But we should really think about finding a dedicated photo repository for the atlas (e.g. flickr?).

**Comment by dbl3raf** [comment]
great, thanks. With the photo - is it already set up to display the photo in the species account, or is that functionality still not available? What should I name the image file so that it appears in the species account?

**Comment by dbl3raf** [comment]
I figured out the photos :-)

**Comment by jeffreyhanson** [comment]
Brilliant!

**Comment by jeffreyhanson** [comment]
Feel free to reopen this issue if you have any questions about editing the magpie goose account.
