### ISSUE TITLE
some grid squares missing?

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#74]
![bald hills](https://user-images.githubusercontent.com/23551540/45949916-f3787d80-c040-11e8-9597-9098e19d92d3.JPG)
The attached shows a missing grid square, and I'm wondering if this could be occurring quite commonly around the edge? Basically, if any grid square intersects the Brisbane LGA boundary, it should be included in the atlas, even if it only intersects it by a tiny amount.  Every part of the LGA should be in a grid square - here the border runs along the South Pine River.

**Comment by dbl3raf** [comment]
you can see several missing squares in this map from the rainbow lorikeet species account
![ralo](https://user-images.githubusercontent.com/23551540/45950082-a21cbe00-c041-11e8-8b0b-aa518c70bbac.JPG)

**Comment by jeffreyhanson** [comment]
Ok, I'll get on this - it will take about a day to remake all the graphs/figs/tables/maps after I update the code.

**Comment by jeffreyhanson** [comment]
Ok I've fixed this - every single grid cell that partially overlaps with the Brisbane LGA is now included (e.g. http://brisbanebirds.com/magpie-goose-anseranas-semipalmata.html#magpie-goose-anseranas-semipalmata) - so I'll close this now.
