### ISSUE TITLE
FAQs in wiki

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#75]
@dbl3raf, can you take a look at the list of FAQs (https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions) and see if you can think of any missing?

**Comment by dbl3raf** [comment]
brilliant - everything I could think of is in there Jeff

**Comment by jeffreyhanson** [comment]
Great - thanks - I'll work on finishing it off then.

**Comment by dbl3raf** [comment]
Another one has just occurred to me "How do I remake the images for the Atlas surveyor sheet?"

**Comment by jeffreyhanson** [comment]
Ok - I'll add that to the FAQs

**Comment by jeffreyhanson** [comment]
I'll close this now, but if you have any more suggestions for FAQs, please feel free to open a new issue.
