### ISSUE TITLE
Fix bug - ghost LGA boundary

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#76]
The LGA boundary stays on as a ghost image in some instances. This has repeatedly happened when I've zoomed in, clicked the grid map on, and then zoomed out again or panned around. Quite frequently, the LGA boundary will remain displayed on the screen - see attached screen shot.
![bug](https://user-images.githubusercontent.com/23551540/46079000-26ee1000-c1d9-11e8-85ab-3c307c728756.JPG)

**Comment by jeffreyhanson** [comment]
I'm having trouble reproducing this bug on my system - which browser are you using? I'e tried Chrome (version 69.0.3497.100) and Firefox (version 62.0).

**Comment by dbl3raf** [comment]
Firefox 62.0.2

**Comment by dbl3raf** [comment]
weird I can't get it to reproduce now either - maybe park this until / if it reappears?

**Comment by jeffreyhanson** [comment]
Hmm, if we're both testing this on eduroam, maybe it only appears on slower internet connections? Ok sounds good, I'll close this now - please reopen this if you can reproduce it.
