### ISSUE TITLE
Spelling in FAQ

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#77]
To keep the atlas consistent, I would suggest mandating that either US or English spelling be used for the entire atlas. If you agree, I can detail the preferred spelling in the FAQ section - do you have a preference?

**Comment by dbl3raf** [comment]
definitely - I reckon we should specify Australian English (then we'll leave it up to contributors to work out what they reckon that means!)

**Comment by jeffreyhanson** [comment]
Ok - can do.
