### ISSUE TITLE
find way to easily search through the species accounts

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#78]

**Comment by Louis-Backstrom** [comment]
I know it was mentioned as being a pain / not necessarily possible but it would be really good to be able to move all the species accounts out of the top folder so that it's easier to search through and find all the other files (like the index, references files, etc.). Alternatively - is there a way to change the names of the other files so they appear first (or do something like pin them to the top of the list in Atom?)

**Comment by jeffreyhanson** [comment]
Yeah I agree. Unfortunately, AFAIK it's bit tricky to do this in bookdown. I just installed this file search add-on for atom (https://atom.io/packages/tree-view-search-bar) and it looks like it would fix 99% of the problem (or it does for me at least). It adds a search bar to the top of the directory tree and you can type in part of filename you want it only shows matching files in the tree. Can you give that a go and see if it makes things easier for you?

**Comment by Louis-Backstrom** [comment]
I've just installed that package - looks to be a start for sure. I'll see how it goes.

**Comment by dbl3raf** [comment]
are we happy to close this issue for now?

**Comment by dbl3raf** [comment]
As far as accessibility of species accounts via the web version is concerned, the list on the species account page is a possible way of doing this - we could divide it up with headers for families etc

**Comment by Louis-Backstrom** [comment]
Searching through on the web is a bit annoying at the moment - the species list is only open when you're on the species accounts page, which means if you want to swap from one species to another you have to either click through the arrows (which isn't helpful if you want to go from species #15 to #270 for example, but works fine if you're just flicking through), or you have to go back to the species account page and then scroll down to wherever you want. I think it would be good to have a search function or something that just makes site navigation a little bit easier. Not sure what the easiest option in bookdown is.

**Comment by jeffreyhanson** [comment]
Yeah, that's true. Unfortunately, if we want to search across different species accounts using the search box in bookdown, it looks like each species will have to be its own chapter (e.g. like Acknowledgement, Methods, Brisbane's Environment). But this means we lose the nice hierarchical organisation of the atlas. What do you think?

**Comment by Louis-Backstrom** [comment]
Hmm, that's annoying. Is there no other way we can improve it somehow?

**Comment by jeffreyhanson** [comment]
I've updated the website to show all the species accounts in the sidebar. This means you should be able to search for a species using the search bar at the top, or simply using the search functionality built in your browser (i.e. `ctrl+f`). Do you think this is an improvement?

**Comment by Louis-Backstrom** [comment]
Definitely an improvement I think - 2 things.

1. It doesn't seem to work at the moment - 
![image](https://user-images.githubusercontent.com/44354406/49579473-1061f300-f998-11e8-8fb7-b54d981aff46.png)

I can't actually get any of the species to turn up when I search. "magp" should turn up 3 species (magpie goose, australian magpie and magpie-lark), but currently it only finds two of the general pages. 

2. Could we maybe tab indent the species accounts so it's clear that they're sort of "underneath" the broader species accounts page?

**Comment by jeffreyhanson** [comment]
1. Yeah that's not right. Thanks for catching that but I don't know how to fix this. I guess we could disable the search bar and just tell people to `crtl+f` the species they want?

2. Perhaps. But if we indent species names in the table of contents (e.g. by adding an invisible UTF8 characters) this will also indent the species names in the title - so I think this would be undesirable?

**Comment by Louis-Backstrom** [comment]
1. I think that probably works well yeah - that's what I've been doing. Other idea would be to try @dbl3raf suggestion of grouping into families or something to make it a little easier to sort through.

2. That's probably not ideal, no...

**Comment by jeffreyhanson** [comment]
Hmm, I like the idea of grouping species together. But if we group species into families than we lose the ability to `crtl+f` all the species. Which approach do you think most users would find easier for searching/discovering species?

**Comment by dbl3raf** [comment]
I think grouping by family works for folks who navigate by mouse - they can click on a family to expand it etc. But at this stage of the Atlas, I think the rapidity of CTRL-F is superior. So I vote for leaving this as it now is, and closing this issue, at least for now.
