### ISSUE TITLE
Naming all Grid Squares

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#79]
I've gone through today and given all the land-intersecting (ie not ocean) squares a unique name according to their location in order to make them easier for people to remember and compare etc. These are stored under the grid folder - grid.dbf now has a new attribute called "display" with all the names.

Unfortunately I also have no idea how to use GitHub to push/pull it back into the project, so I can't upload the changes :(

Here's what it looks like in QGIS:
![image](https://user-images.githubusercontent.com/44354406/47560576-f32f1300-d95b-11e8-816c-09123579b5bb.png)

**Comment by dbl3raf** [comment]
brilliant work @Louis-Backstrom - I've copied the names into the "name" field of grid.dbf for all cases where "display" was not null, and replaced the old version of grid.dbf in the master. Next time we build the maps, the names of the grid cells should appear.
