### ISSUE TITLE
Spreadsheet with species names to be included in atlas

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#8]
This spreadsheet should have a column "species_scientific_name" (which corresponds Clements list used by eBird), and then an "index" column showing the order for each species (lower numbers appear earlier in the book)

**Comment by dbl3raf** [comment]
note there's a grab-bag of species at the end - those that have been recorded as escapes from captivity - we'll need a different page format for writing about these.

[atlas_list.xlsx](https://github.com/bird-team/brisbane-bird-atlas/files/2033233/atlas_list.xlsx)
