### ISSUE TITLE
Decide on the referencing system to be used

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#85]
Current system is Methods in Ecology & Evolution (I think) - no problem with this. More wondering if we should have a consistent system of linking to the references in the .Rmd files from the bib file. Current '@ article' names are 'rexample1', 'rexample2', etc., plus '[author][year][journal]' format from the two test ones I've just added for Magpie Goose. Would be good to have a consistent system for the majority of these to facilitate linking in the text. I think the [author][year][journal] format works well as a) it makes sense and b) it seems to be what google scholar outputs by default. 

For the references which get heavy use across multiple pages (thinking HANZAB volumes, the current 'r1' eBird reference, ABG, etc.) these could have other names (for instance 'HANZABv1'), but I think it will be easier in the long term to get a good system going early.

**Comment by jeffreyhanson** [comment]
Yeah, I agree it's important to come up with a referencing system that makes sense and will minimise mistakes. The only problem I can think of with `[author][year][journal]` is in situations where the same author has published multiple papers in the same year in the same journal. Although this is pretty unlikely, it might be good to come up with a referencing system that explicitly accounts for this - what do you think? Maybe you could just add a letter or number at the end of the identifier?

**Comment by Louis-Backstrom** [comment]
I think a number would work well yeah - so [author][year][journal][#]. As you say, relatively unlikely although quite probable it will come up at least once.

**Comment by Louis-Backstrom** [comment]
On closer inspection, it seems google scholar's default output is `[author][year][first word of title]` which arguably works better - happy to leave it at that instead of `[journal]` ?

**Comment by jeffreyhanson** [comment]
Yeah, I don't really mind which system you use - I think it's best to find a system that works best for you and @dbl3raf - what do you think @dbl3raf?

**Comment by dbl3raf** [comment]
I'm happy with [author][year][first word of title] where [first word of title] is taken to mean the first substantive word (as I see you've already done @Louis-Backstrom. But I reckon we should only disambiguate by adding a number if a duplicate occurs. There will be vanishingly few occurrences of a duplicate with this naming convention and it seems wasted time to add a 1 to every reference just in case it happens. Let's just add a 2 if a duplicate comes up.

**Comment by dbl3raf** [comment]
I think even for HANZAB we should still use the same convention - if we always stick with it, then there will be less confusion.

**Comment by dbl3raf** [comment]
What code do we use for citing a website? I could easily see it in the style file? But maybe there's a way to use misc? We'll be citing eBird checklists a lot, and I think we should add them as normal references, e.g:

@alexander2015ebird

Alexander C (2015) eBird Checklist: http://ebird.org/view/checklist/S24319461. eBird: An online database of bird distribution and abundance. eBird, Ithaca, New York. (Accessed: 5 November 2015).

There might be quite a few duplicates with that particular referencing system, since the first word of all refs will be ebird, but we can try it and see if it works. the other option is that for eBird checklists we use @alexander2015S24319461 - that way we'll never have duplicates and I suppose it's a more bulletproof way of avoiding errors. Thoughts?

**Comment by jeffreyhanson** [comment]
Yeah, you would use `@misc` for websites. This reference type can be a bit unpredictable though, but maybe something like this would work if you wanted that exact format:

```
@misc{alexander2015ebird,
  title={{eBird Checklist: http://ebird.org/view/checklist/S24319461}},
  author={Alexander, C},
  year = {2015},
  note={{eBird: An online database of bird distribution and abundance. eBird, Ithaca, New York. (Accessed: 5 November 2015).}}
}
```

**Comment by Louis-Backstrom** [comment]
I think @dbl3raf suggestion of just adding the identifier when there are duplicates is good. I guess making it the same for all (ie including HANZAB) works too. My only concern is with the file itself - I can see it getting very long when we reach ~1000+ references (which I think will definitely happen if we're referencing eBird checklists too), and there doesn't seem to be a good way of sorting all the references within the `references.bib` file. Not sure how we would approach this, especially for papers that get used for multiple species but not necessarily at the same time (e.g. we add a paper for Magpie Goose now, and then want to use the same paper for the Black Swan (or whatever) in a year's time, forgetting that we've already put it in the references file, thus creating duplicates?).

I think Richard's suggestion of adding the checklist number to the end of the identifiers for eBird references is a good start.

**Comment by dbl3raf** [comment]
it'll be important to search CTRL-F when adding a new reference to make sure it isn't already in there. We could try to enforce having everything in alphabetical order in the references.bib file. Although it will be hard to police accurately, we could at least tidy up parts of it every now and then - that will also help identify duplicates. And if duplicates go in, it's not the end of the world. Most important will be checking that the proposed identifier isn't a duplicate.

**Comment by Louis-Backstrom** [comment]
Yeah, that sounds good. @jeffreyhanson what actually happens if there are two identifiers that are the same? Does the code crash?

**Comment by Louis-Backstrom** [comment]
I've added the eBird checklists already mentioned into the references file. Now that we have a basis for the referencing system to be used I think this issue can be closed until we have another issue with it.
