### ISSUE TITLE
Formatting text in references 

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#86]
@Louis-Backstrom I just noticed you were adding references for the magpie goose - awesome work! I forgot to mention this, but since the references are processed using Bibtex, I think you might need to use the `\textit` command to italicise text and the `\textbf` command to bold text. For example `\textit{Anseranas semipalmata}` and `\textbf{Anseranas semipalmata}`. I had a look at the page for the [magpie goose](https://brisbanebirds.com/magpie-goose-anseranas-semipalmata.html#magpie-goose-anseranas-semipalmata) and it looks like standard markdown commands like `**` and `*` aren't working.

**Comment by Louis-Backstrom** [comment]
Which parts of the references need to be italicized? Is it the whole citation? Currently in the first Magpie Goose reference it seems _et al_ is and nothing else, but I'm not familiar enough with the referencing style we're using to know.

Also, could the reference-style.bst or csl files be modified to do this?

**Comment by jeffreyhanson** [comment]
Specifically, you would need to use the `\textit` and `\textbf` commands for any text that you want formatted differently than the default formatting for that field in the citation. For example, paper titles are just formatted with plain text. So if you have a species name in a paper title, and you want the species' name in the paper title to be italicised, you will need to encapsulate the species' name in the `\textit` command. Similarly, journal names are italicized by default under this reference format, but if you wanted to make some of the text bold, you would need to use the `textbf` command. It might be possible to modify the reference-style.bst/csl files to do this, but I don't know how to do this. 

Also, I see that you updated the reference file with the `\textit` command, this should work, but it's not appearing on the website yet because the build hasn't completed (see here for progress https://circleci.com/gh/bird-team/brisbane-bird-atlas/tree/master).

Just to provide a complete example, here's an example of a Bibtex reference that italicises the species' name and makes the "text" word in the journal's name shown in bold. Also, just in case I forgot to mention earlier any `&` symbols need to be represented as `\&` (as in the `publisher` field below).

```
@article{nye2007wild,
  title={A wild goose chase—temporal and spatial variation in the distribution of the Magpie Goose (\textit{Anseranas semipalmata}) in Australia},
  author={Nye, Errol R and Dickman, Chris R and Kingsford, Richard T},
  journal={Emu \textbf{text}},
  volume={107},
  number={1},
  pages={28--37},
  year={2007},
  publisher={Taylor \& Francis}
}
```

**Comment by Louis-Backstrom** [comment]
Alright that makes more sense - I'll see what it looks like once the build has gone through.

**Comment by Louis-Backstrom** [comment]
Looks good to me - references still need a bit of editing (couple of missing capitalizations etc) but the italics are there. I'll go through now and make the whole page look nice and have a look then.

**Comment by Louis-Backstrom** [comment]
It seems the capitalization is happening through the formatting, and not from within the `references.bib` file - here's what the .bib has:

```
@article{nye2007wild,
  title={A wild goose chase—temporal and spatial variation in the distribution of the Magpie Goose (\textit{Anseranas semipalmata}) in Australia},
  author={Nye, Errol R and Dickman, Chris R and Kingsford, Richard T},
  journal={Emu},
  volume={107},
  number={1},
  pages={28--37},
  year={2007},
  publisher={Taylor \& Francis}
}
```

And here's what the output is on the website:

![image](https://user-images.githubusercontent.com/44354406/47958946-00b26000-e022-11e8-9358-00d0066a1eb5.png)

It seems that the format of the references is to only capitalize the first word in the title, regardless of whether subsequent words are in caps in the actual .bib file or not - can we change this?

**Comment by jeffreyhanson** [comment]
Yeah, the reference-style files automatically try to handle caps and non-caps. To enforce caps, or non-caps, you can enclose the relevant text in `{` and `}`. For example,

```
@article{nye2007wild,
  title={{A wild goose chase---temporal and spatial variation in the distribution of the Magpie Goose (\textit{Anseranas semipalmata}) in Australia}},
  author={Nye, Errol R and Dickman, Chris R and Kingsford, Richard T},
  journal={Emu},
  volume={107},
  number={1},
  pages={28--37},
  year={2007},
  publisher={Taylor \& Francis}
}
```

**Comment by Louis-Backstrom** [comment]
Alright - I'll see if that's fixed it now then

**Comment by dbl3raf** [comment]
all fixed up - looking good, I'll close the issue
