### ISSUE TITLE
Change Grid Square #9972's Name

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#87]
I must have missed it or something because currently its display name is "F" and I'm not entirely sure why. I think it should be called Strathpine, and I would change it myself but I haven't worked out how to change the `grid.shp` file without breaking the rest of it...

**Comment by dbl3raf** [comment]
No worries I’ll get on it tonight - all good practice for me

**Comment by dbl3raf** [comment]
I'm running a rebuild overnight - managed to (successfully I think) update to the August 2018 eBird download and am building assets overnight.

**Comment by dbl3raf** [comment]
Solved with new build finished just now
