### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#89]
I just wanted to let you know that the most recent commit 38839a31beca6f00e52b1c0c6217d4847b45e89c broke the build - it looks like this just involved changing the _data/species/atlas_list.xlsx_ file.

**Comment by jeffreyhanson** [comment]
If we look at the log file (https://api.travis-ci.org/v3/job/452043606/log.txt), then these lines suggest that the species "Pluvialis dominica" is missing a map in the assets-maps.zip archive:

```
Quitting from lines 5631-5632 (brisbane-bird-atlas.Rmd) 
Error in render_species_map(species_name) : 
  assets/maps/Pluvialis-dominica.png does not exist
Calls: system.time ... withCallingHandlers -> withVisible -> eval -> eval -> render_species_map
```

**Comment by jeffreyhanson** [comment]
I just double checked and "Pluvialis dominica" is indeed missing a map file in the _assets-maps.zip_ archive (although it does have a hash file suggesting that it did have a map at one point in time).

**Comment by jeffreyhanson** [comment]
@dbl3raf, is it possible that the assets might need to be remade so that every species that is supposed to have a map according to the spreadsheet also has an image in the _assets-maps.zip_ archive?

**Comment by dbl3raf** [comment]
yep I've tried remaking the assets but it failed and I haven't pushed the rebuild yet - all to do with missing maps, I'll look into it again tonight

**Comment by Louis-Backstrom** [comment]
Isn't _Pluvialis dominica_ the American Golden Plover? Should that even be in the `atlas_list.xlsx` file?

//Edit Just went through the August 2018 data and couldn't find any record of AGP in there - is there a reason then that it's on the species list?

**Comment by dbl3raf** [comment]
it can be deleted - there are specimens in QM catalogue with Brisbane coordinates, but I think these are errors

**Comment by jeffreyhanson** [comment]
Ah ok - no worries - I just wanted to make sure everyone knew about the build failure. @dbl3raf and @Louis-Backstrom, did you receive an email from Travis or CircleCI about the failure?

**Comment by Louis-Backstrom** [comment]
I did not get an email - I think the only emails I get are from GitHub. //Edit: I get CircleCI notifications when my own build fails, just not for others by the looks of it

I'll go through now and delete the AGP line from the excel file, see if that fixes the issue.

**Comment by Louis-Backstrom** [comment]
It's run into another problem:

```
Quitting from lines 5601-5602 (brisbane-bird-atlas.Rmd) 
Error in if (is.na(path)) path <- "assets/misc/missing-profile.png" : 
  argument is of length zero
Calls: system.time ... withVisible -> eval -> eval -> render_species_profile

Timing stopped at: 27.15 0.78 27.57
Execution halted
Exited with code 1
```

It possibly just needs the assets to be rebuilt before it makes the website again, but I can't do that on my computer - @dbl3raf or @jeffreyhanson ?

**Comment by dbl3raf** [comment]
I'll have a go at rebuilding the assets tonight unless Jeff gets to it before - I shouldn't have committed the new species spreadsheet without having finished rebuilding and pushing the assets!

**Comment by jeffreyhanson** [comment]
Yeah it probably just needs the assets - I don't think this is particularly urgent - so maybe we can just wait until Rich rebuilds them this evening?

Ok - I'll update the Travis config file to send email notifications about build failures. @Louis-Backstrom can you please let me know which email address you would like to receive the emails at?

**Comment by jeffreyhanson** [comment]
I've just added @dbl3raf to the build notifications (4cf6ae39d60f95e10bb08fb87997adc3375c3d14), but you might have to link your Github account with TravisCI to start receiving them (https://docs.travis-ci.com/user/notifications/#missing-build-notifications)

**Comment by dbl3raf** [comment]
I'm already getting emails from Travis - thanks

**Comment by Louis-Backstrom** [comment]
I've just added my email address too, and my GitHub account is linked to CircleCI (I think), so hopefully I'll get build notifications too.

**Comment by jeffreyhanson** [comment]
Ok - great!

**Comment by dbl3raf** [comment]
When American golden plover was removed, the entry for Pluvialis dominica in the bookdown.yml should also have been deleted - it was trying to build with assets that didn’t exist. It’s now building successfully so I’ll close the issue

**Comment by jeffreyhanson** [comment]
Ah ok - thanks for resolving this. I wonder if there's anything I can do to help make tracking doing build failures easier? E.g. the atlas list data are stored in an excel spreadsheet so we can't easily track changes to it via GitHub - if we changed it to a csv then we could see which rows/values were changed between different commits?
