### ISSUE TITLE
Requesting single map causes error in asset build

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#90]
I figured that for many of the rarest species, we would only want a single map - the detection map - map 6. I tried specifying this in the species table, but it causes an error on the widget build (the maps themselves build just fine).

I tried having just 6 in the field, also tried 6_ and _6 and _6_ and none of them worked. Maybe there's a fundamental reason why I can't just have a detection map alone? Maybe it makes null widgets?
![image](https://user-images.githubusercontent.com/23551540/48196127-4a41d880-e39d-11e8-99de-d27c030fc728.png)

**Comment by dbl3raf** [comment]
had the same error with 1_6 selected in map field, but not when the map field was left blank

**Comment by Louis-Backstrom** [comment]
Does 6_6_6_6_6_6 work perhaps? Although maybe that would just duplicate the detection six times. Worth a shot?

**Comment by dbl3raf** [comment]
For now I’ve reverted them to all maps just to stabilise the build

**Comment by jeffreyhanson** [comment]
Ok, thanks for providing the error message and looking into it, I'll see if I can fix it.

**Comment by jeffreyhanson** [comment]
To reproduce this bug, do I just need to clone the latest version of the repo? Or is there anything else I need to do (e.g. are there data on your computer that haven't been pushed)?

**Comment by dbl3raf** [comment]
Just a clone - everything is pushed from me

**Comment by jeffreyhanson** [comment]
Ok, I've updated the script for making the widgets and it now works for _Radjah radjah_ (with a value of just 6 in the `maps` column of `data/species/atlas_list.xlsx`) - can you pull the latest version and try rebuilding the assets on your computer?

**Comment by dbl3raf** [comment]
Thanks Jeff - success! I updated Radjah shelduck and the website build completed successfully. Closing issue.

**Comment by jeffreyhanson** [comment]
Ok - brilliant!
