### ISSUE TITLE
builds failing - missing header in index.Rmd

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#93]
@dbl3raf, I see you that you removed the `# Preface` chapter level heading in e454f86a914e7484d1d8817372711b8fd240d641. This is causing the builds to fail because the `index.Rmd` file needs a chapter (`#`) or section (`##`) level heading (see https://circleci.com/gh/bird-team/brisbane-bird-atlas/166). Could you please edit a heading back into `index.Rmd`? Perhaps "Overview" or "Welcome" might work?

**Comment by Louis-Backstrom** [comment]
I've added a chapter level heading back to the `index.Rmd` file, @dbl3raf feel free to change it
