### ISSUE TITLE
Formatting of paragraphs

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#94]
Definitely more of a "nice to have" thing, but is it possible to change the paragraphs to justify instead of left-aligned? I think it looks a bit nicer - see this example:
![image](https://user-images.githubusercontent.com/44354406/48536425-4c0a1f80-e8fa-11e8-85dd-cbe4e23a34e7.png)

**Comment by jeffreyhanson** [comment]
I've just made a commit that might do it. Once it finishes rebuilding the website, we can see if it worked.

**Comment by Louis-Backstrom** [comment]
That commit appears to have fixed it for the book but not the website - book's looking great though! Title page needs a fix up...

**Comment by jeffreyhanson** [comment]
I just had a quick look at the website and the text (e.g. on this page: https://brisbanebirds.com/wandering-whistling-duck-dendrocygna-arcuata.html#wandering-whistling-duck-dendrocygna-arcuata) looks justified on my browser (Google Chrome version 70.0.3538.102) - which browser are you using?

I'll see what I can do about the book.

**Comment by Louis-Backstrom** [comment]
Weird - looks good to me now. Much better.
