### ISSUE TITLE
Species profile sizing

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#99]
At the moment, the species' profile images in the pdf version of the book are scaled to increase/decrease the image until it fits the width of the page. This means that the height is variable. Looking at some species, e.g. the Musk Duck, the present configuration results in the profile picture taking up half the page. I just wanted to ask if this is desirable? Or should the images be scaled such that the image must fullfill a maximum height criteria and must also not exceed the page width?

![musk-duck](https://user-images.githubusercontent.com/3610005/48680304-9aaf0680-ebe5-11e8-9aa9-05e917c78b42.png)

**Comment by Louis-Backstrom** [comment]
I know Rich and I had a bit of discussion about this earlier - both about the sizing and the aspect ratio of the images. Currently the images in the Flickr album aren't standardised re aspect ratio - some of them are quite rectangular (e.g. Magpie Goose) - probably close to 2:1 ratio, but most of them are just whatever came out of the camera - which is usually 3:2 and therefore much more square. That's what the Musk Duck image looks like at a guess. 

It would be good to standardise this some way - I had a look to see if it was easy to do on Flickr and concluded that it was possible but a fair pain - every change you make to the image (ie cropping it to the new ratio) changes the web url so you'd have to update the excel file for each change. In future, I think we should make sure all photos (at least all species photos - not sure what we want to do about habitat shots etc.) are cropped to the desired ratio and zoom before they get uploaded - unless there's a way to do this via Bookdown or something @jeffreyhanson ?

I think a ratio of 16:9 is probably best - it's pretty wide so wouldn't cause issues like the one above, plus it's a pretty standard ratio (most laptop/phone screens these days are 16:9). Thoughts?

**Comment by dbl3raf** [comment]
they should all be Facebook profile aspect ratio - 1200 x 630 - this will help them not take up too much space. Need to get through Flickr and sort them all out

**Comment by jeffreyhanson** [comment]
Yeah I don't think there is an easy way to automatically extract the picture of the bird out of the image with a pre-defined aspect ratio, so this would have to be something done manually. Yeah, I agree the best strategy would be to handle the image cropping before uploading them and then using the url for the cropped image in the spreadsheet. Yeah I could make it so that the images are stretched to 1200 x 630 - but this would probably look really ugly. So, is the current default behaviour ok then since it will make spotting the uncropped images fairly easy?

**Comment by Louis-Backstrom** [comment]
I think it is probably easiest to do it manually yeah. I'm not sold on 1200x630 - this seems to be a very arbitrary number? Especially given that we're not pulling images off Facebook (or pushing them to it) - 40:21 is a bit strange. Perhaps we could simplify that to 2:1? Wouldn't really be a noticeable difference (but if anything would reduce the space even more) but it's a much easier number to work with.

**Comment by dbl3raf** [comment]
my thought was that Facebook will have researched image sizing carefully. But I'm happy to go with 2:1 - this is indeed a much simpler approach. Yes @jeffreyhanson let's not stretch the images in the PDF build, rather we'll make sure they are all sized 2:1 in the Flickr album.

**Comment by dbl3raf** [comment]
I just had a look at cropping an image and 2:1 is a bit too extreme I think.

Can we please go with 16:9 as originally suggested by @Louis-Backstrom - I think it's the best compromise, and it is the standard wide screen aspect ratio. I am about to upload a new magpie goose profile pic so we can see how it progresses through the build.

**Comment by dbl3raf** [comment]
seems to build OK, and it fits beautifully, but it takes up a bit too much vertical space. We'll have to try and condense the caption and opening summary paragraph to try and free up some real estate on the page of species account prior to the page with the display items

**Comment by dbl3raf** [comment]
awaiting resolution of #101 before checking whether the PDF pagination is corrected to stop the first page of each species account spilling onto a second. Once confirmed, we can set approximate limits to the size of the opening paragraphs on the first page of the species accounts, unless anyone also has other ideas about how we can create some more space on that first page?

**Comment by dbl3raf** [comment]
I’ve edited all the photos on Flickr to 16:9 but I think this causes the URL to change - might need to update species xlsx to reflect new URLs if this has occurred

**Comment by Louis-Backstrom** [comment]
I've gone through and updated all the urls - unless there's a further error, I'm closing this for now

**Comment by jeffreyhanson** [comment]
Awesome work @Louis-Backstrom and @dbl3raf!
